### ISSUE TITLE
Can't disable multithreading in parse_many after compiling simdjson with thread support

### ISSUE THREAD

**Issue by MaxBareiss** [simdjson/simdjson#988] opened 2020-06-25 15:29 UTC
Before submitting an issue, please ensure that you have read the documentation:

* Basics is an overview of how to use simdjson and its APIs: https://github.com/simdjson/simdjson/blob/master/doc/basics.md
* Performance shows some more advanced scenarios and how to tune for them: https://github.com/simdjson/simdjson/blob/master/doc/performance.md
* Contributing: https://github.com/simdjson/simdjson/blob/master/CONTRIBUTING.md

**Describe the bug**
When I use this code to disable the multithreaded path:

```C++
#undef SIMDJSON_THREADS_ENABLED
#include "simdjson.h"
```

It still uses the multithreaded code path, as shown in a backtrace. I want to disable the multithreaded code path because I'm using multiple threads in my application to parse multiple files.

How am I supposed to disable threading in simdjson?

**To Reproduce**
```C++
#include <iostream>
#include <fstream>
#include <unistd.h>
#include <sys/stat.h>
#include <thread>
#include <filesystem>
#include <chrono>

#undef SIMDJSON_THREADS_ENABLED
#include "simdjson.h"

int main(int argc, char** argv){
    using namespace simdjson;
    for (auto& _path: std::filesystem::directory_iterator("json_data_1")){
        dom::parser parser;
        std::string path = _path.path();
        for (dom::element row : parser.load_many(path)){
            try{
                double value = row["value"];
            } catch (simdjson_error){
                return 1;
            }
        }
    }
}
```

**Configuration (please complete the following information if relevant):**
 - OS: [e.g. Ubuntu 16.04.6 LTS]
 - Compiler [e.g. Apple clang version 11.0.3 (clang-1103.0.32.59) x86_64-apple-darwin19.4.0]

OS: Arch on June 24, 2020 x86_64
Compiler: Both clang 10.0.0 and gcc 10.1.0 have this issue.
Version: 0.4.0

**Indicate whether you are willing or able to provide a bug fix as a pull request**
I will update the documentation.

If you plan to contribute to simdjson, please read our 
* CONTRIBUTING guide: https://github.com/simdjson/simdjson/blob/master/CONTRIBUTING.md and our
* HACKING guide: https://github.com/simdjson/simdjson/blob/master/HACKING.md

**Comment by lemire** [comment] 2020-06-25 15:35
The issue is correct, you cannot disable multithreading. I removed the "bug" label because this is not a bug: we do not offer the promise that you can disable multithreading.

Your issue is effectively a duplicate of https://github.com/simdjson/simdjson/issues/925

**Comment by furkanusta** [comment] 2020-06-25 15:37
I had encountered this when I was working on the CMake files but I suppose I forgot to open an issue. 
SIMDJSON_THREADS_ENABLED gets defined whenever the library is linked with pthread, regardless of the cmake variable SIMDJSON_ENABLE_THREADS

https://github.com/simdjson/simdjson/blob/c25928e44fb69f5a3b1d0bbbabf75742e15269ee/include/simdjson/portability.h#L119-L122

**Comment by lemire** [comment] 2020-06-25 15:50
@furkanusta 

> I had encountered this when I was working on the CMake files but I suppose I forgot to open an issue.
SIMDJSON_THREADS_ENABLED gets defined whenever the library is linked with pthread, regardless of the cmake variable SIMDJSON_ENABLE_THREADS

That's the intention. 

Remember that we do not know that the user is compiling simdjson using CMake.

Currently, the intention is that... if you are compiling simdjson with thread support, we enable threads. Period. We do not want just enable threads when the proper macro is passed. 


What we lack is that ability at the API level to give you control regarding whether we use threads or not.

**Comment by lemire** [comment] 2020-06-25 15:51
Note that I am not dismissing the issue. We are planning to fix this in the next release. I have been aware of the problem, but we fixed more urgent problems.

**Comment by jkeiser** [comment] 2020-06-25 17:03
@furkanusta agreed that you should be able to disable it. May I ask what your personal thoughts are on why you'd like to? I know there can be good reasons, I just want to gather yours too :)

**Comment by MaxBareiss** [comment] 2020-06-25 17:23
I am running through a lot of files, and each one contains one json object per line. I have my own thread pool, one thread per core, which runs through the files. simdjson produces more threads per core, and I wanted to investigate the performance impact of that.

**Comment by jkeiser** [comment] 2020-06-25 17:33
> I am running through a lot of files, and each one contains one json object per line. I have my own thread pool, one thread per core, which runs through the files. simdjson produces more threads per core, and I wanted to investigate the performance impact of that.

Absolutely makes sense :) We've been talking about a runtime switch, but it might not be the first thing we get to for 0.5. For now, if you would like to add the ability to specify this in cmake so you can easily switch it back and forth to investigate, it'd be welcome!

**Comment by jkeiser** [comment] 2020-06-25 17:34
(And we'd love to find out what you learn.)

@MaxBareiss just checking one thing: are you keeping the parser around for the life of the thread, or declaring a new `dom::parser` for each json file? You will run significantly faster if you do the latter :)

**Comment by MaxBareiss** [comment] 2020-06-25 17:57
@jkeiser I make a new parser for each file. I'm using a canned thread pool library, so I'd have to do some re-writing do that correctly. I tried a simple way of making a parser for each thread and it runs slower.

**Comment by lemire** [comment] 2020-06-26 17:31
I am adding a temporary, runtime option, SIMDJSON_DO_NOT_USE_THREADS_NO_MATTER_WHAT.

We will not support this option long term since our goal is to give you, at runtime, the support you need.

This should be part of release 0.4.1.

**Closed** 2020-06-26 22:37 UTC
Labels: enhancement
