### ISSUE TITLE
One-time CI sanitize failure in document_stream_tests

### ISSUE THREAD

**Issue by jkeiser** [simdjson/simdjson#1370] opened 2021-01-05 17:57 UTC
document_stream_tests on Clang 9 (fallback implementation) [failed sanitization](https://cloud.drone.io/simdjson/simdjson/7594/8/2):

```
+ SIMDJSON_FORCE_IMPLEMENTATION=fallback ASAN_OPTIONS="detect_leaks=0" ctest $CTEST_FLAGS -L per_implementation
--
740 | Test project /drone/src/build
741 | Start 22: json2json
742 | Start  8: document_stream_tests
743 | Start  6: random_string_number_tests
744 | Start  9: document_tests
745 | 1/27 Test #22: json2json ........................   Passed    0.02 sec
746 | Start 20: testjson2json
747 | 2/27 Test  #8: document_stream_tests ............***Failed    0.05 sec
748 | Running tests against this implementation: fallback(Generic fallback implementation)
749 | ------------------------------------------------------------
750 | Running document_stream tests.
751 | Running stress_data_race
752 | Running stress_data_race_with_error
753 | Running test_leading_spaces
754 | Running simple_example
755 | got full document at 0
756 | got full document at 9
757 | got full document at 29
758 | Running truncated_window
759 | got full document at 0
760 | got full document at 9
761 | Running truncated_window_unclosed_string
762 | A string is opened, but never closed.
763 | Running issue1307
764 | hex  : 02 00 0C 00 20 00
765 | ascii:  __ __ __ __ __ __
766 | Running issue1308
767 | hex  : 6D C7 6D 5B 41 00
768 | ascii: m__ __m__[__A__ __
769 | Running issue1309
770 | hex  : 09 00 39 38 0A 39 0A 0A 0A 0A 22 22 5F 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 5F 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 DB DB DB DB DB DB DB DB DB 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 00
771 | ascii:  __ __9__8__ __9__ __ __ __ __"__"_____"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"_____"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__ __
772 | Running issue1310
773 | hex  : 20 20 5B 20 33 2C 31 5D 20 22 22 22 22 22 22 22 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20
774 | ascii:  __ __[__ __3__,__1__]__ __"__"__"__"__"__"__"__ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __
775 | Running issue1311
776 | hex  : 35 23 30 5B 5B 30 0C FC 00
777 | ascii: 5__#__0__[__[__0__ __ __ __
778 | Running test_naked_iterators
779 | Running test_current_index
780 | Running single_document
781 | Running issue1133
782 | Running single_document_exceptions
783 | Running threaded_disabled
784 | Expected a capacity error No error
```

I'm unsure whether the hex dumps are sanitize failures, but we didn't get a capacity error when we expected one, apparently, and that's the end of the test, so is probably the reason it failed. Intermittent failures are possible in document stream tests, because there are threads involved. (Though that test appears to be named threaded_disabled, so ...)

**Comment by lemire** [comment] 2021-01-05 23:05
It is going to be hard to examine it if we can't reproduce it, but it is good report it as a potential bug.

We should not have data races. The threaded code is very well protected in my opinion.

**Comment by jkeiser** [comment] 2021-01-21 20:44
Closing. Haven't seen it myself since.

**Comment by jkeiser** [comment] 2021-01-27 04:53
OK, here it is again:

https://cloud.drone.io/simdjson/simdjson/7796/4/2

Worth inspecting code, at some point.

**Comment by lemire** [comment] 2021-02-01 19:45
So it seems to be clang specific. I will compile a version with master with as many sanitizers as I can,  and I will  the same tests running.

It could be a data race?

**Comment by lemire** [comment] 2021-02-02 15:56
Ok. So looking at the logs, the error seems to always happen in the same test: threaded_disabled. This test is poorly named because it does not disable the threads, I will create an issue to rename it.

```C++
  bool threaded_disabled() {
    std::cout << "Running " << __func__ << std::endl;
    char input[2049];
    input[0] = '[';
    for(size_t i = 1; i < 1024; i++) {
      input[2*i+1]= '1';
      input[2*i+2]= i < 1023 ? ',' : ']';
    }
    auto json = simdjson::padded_string(input,2049);
    simdjson::dom::parser parser;
    size_t count = 0;
    size_t window_size = 1024; // deliberately too small
    simdjson::dom::document_stream stream;
    ASSERT_SUCCESS( parser.parse_many(json, window_size).get(stream) );
    for (auto doc : stream) {
      if (!doc.error()) {
          std::cerr << "Expected a capacity error " << doc.error() << std::endl;
          return false;
      }
      count++;
    }
    if(count == 2) {
      std::cerr << "Expected a single document " << std::endl;
      return false;
    }
    return true;
  }
```

I have run it thousands of times without error. I have tried the data race sanitizer and nothing comes up. I will review manually and issue a PR.

**Comment by lemire** [comment] 2021-02-02 21:14
I am going to close this issue since the failing test no longer exist. I replaced it with a much more extensive test that should provide more information in case of failure.

It is a really strange failure because the test in question is nothing special. It is actually redundant over other tests.

**Closed by lemire** 2021-02-02 21:14 UTC
Labels: bug (unverified)
