### ISSUE TITLE
Fail to compile on demand example from doc

### ISSUE THREAD

**Issue by jpalus** [simdjson/simdjson#1378] opened 2021-01-07 14:02 UTC
I've started looking into transforming  my simple code from DOM to on demand parser but failed pretty quickly. Admittedly C++ is not my strongest side (to put it mildly) but I cannot even get sample from https://github.com/simdjson/simdjson/blob/master/doc/ondemand.md to compile. Exact source file:
```cpp
#include "simdjson.h"
using namespace std;
using namespace simdjson;
using namespace simdjson::builtin; // for ondemand
int main(void) {
  ondemand::parser parser;
  padded_string json = padded_string::load("twitter.json");
  ondemand::document tweets = parser.iterate(json);
  for (auto tweet : tweets["statuses"]) {
    std::string_view text        = tweet["text"];
    std::string_view screen_name = tweet["user"]["screen_name"];
    uint64_t         retweets    = tweet["retweet_count"];
    uint64_t         favorites   = tweet["favorite_count"];
    cout << screen_name << " (" << retweets << " retweets / " << favorites << " favorites): " << text << endl;
  }
}
```
Compilation command:
```
g++ -march=native -o test test.cpp -lsimdjson
```
Error:
```
test.cpp: In function ‘int main()’:
test.cpp:10:48: error: conversion from ‘const char’ to non-scalar type ‘std::string_view’ {aka ‘nonstd::sv_lite::basic_string_view<char>’} requested
   10 |     std::string_view text        = tweet["text"];
      |                                    ~~~~~~~~~~~~^
test.cpp:11:63: error: conversion from ‘const char’ to non-scalar type ‘std::string_view’ {aka ‘nonstd::sv_lite::basic_string_view<char>’} requested
   11 |     std::string_view screen_name = tweet["user"]["screen_name"];
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```
simdjson 0.7.1 (system installed)
OS: Linux
Arch: aarch64
GCC: 10.2.0

Am I missing something?

**Comment by lemire** [comment] 2021-01-07 14:52
So "tweet["text"]" would return a "const char"? That's odd.

**Comment by lemire** [comment] 2021-01-07 14:57
Verified.

**Comment by lemire** [comment] 2021-01-07 14:58
There is clearly an issue with this example.

**Comment by lemire** [comment] 2021-01-07 15:00
It is very odd. It seems like `tweet["text"]` returns a `char`.

**Comment by lemire** [comment] 2021-01-07 15:00
So it is at least a documentation bug.

**Comment by lemire** [comment] 2021-01-07 15:00
Marking at 0.8 so we don't release without resolving this issue.

**Comment by jkeiser** [comment] 2021-01-07 15:37
It's probably worth using some of the examples from the (yet to be merged) [documentation PR](https://github.com/simdjson/simdjson/blob/0039c5b981e7283efa333f1b18920d27540597e3/doc/ondemand.md), which has been better tested.

**Comment by jkeiser** [comment] 2021-01-07 15:40
Oh ... you will probably have a better time if you use master, too. I'll look and see what's going on with 0.7.1.

**Comment by jkeiser** [comment] 2021-01-07 15:44
Yeah, whatever it is is fixed in master. (Still looking.)

**Comment by jpalus** [comment] 2021-01-07 15:45
Comparing with linked PR the main difference seems to be explicit type "ondemand::object" of <anything>[<field>]. If I cast every instance of it, compilation passes.

**Comment by jkeiser** [comment] 2021-01-07 15:47
Another thing that fixes it in 0.7.1 is adding `.get_string()` to both of those lines. I'd obviously rather you not have to do that, though :)

**Comment by jkeiser** [comment] 2021-01-07 15:52
(Never mind, get_string() doesn't fix it, I wasn't running the code I thought I was.)

**Comment by jkeiser** [comment] 2021-01-07 15:59
@jpalus OK, the issue is that 0.7.1 doesn't implement operator[] on `value` types at all ... so C++ casts to const char * and runs [] on that. Oy! That's a doozy! Your `ondemand::object` fix should work fine on 0.7.1.

It's not necessary to use master, but I've added some nice quality of life improvements there (including fixing this). You can get that working by following the [on demand quickstart](https://github.com/simdjson/simdjson#on-demand). Your code should work fine against that.

Let us know if you have any issues or even things that are annoying, I'm excited to get more people using it, and I *definitely* want it to be just as easy as using the DOM. We're seeing massive improvement on everything we've benchmarked so far. Everybody should have access to this level of performance!

**Comment by jkeiser** [comment] 2021-01-07 16:00
(To be clear, on master you won't have to cast to ondemand::object.)

**Comment by lemire** [comment] 2021-01-07 16:01
I have linked the documentation PR with this issue so that when we merge the PR, we will have resolved this issue.

**Comment by jkeiser** [comment] 2021-01-07 16:07
> I have linked the documentation PR with this issue so that when we merge the PR, we will have resolved this issue.

Note that the [example that fails on 0.7.1](https://github.com/simdjson/simdjson/pull/1360/files#diff-e3ba446d89b4ad6f51acc8e6fb9e19246b0d2a1229e2c7a0c6cdbfb255366c3bR26-R36) is still there in that PR. The example compiles without issue on master, though, and is the preferred idiom. Either way, I'd rather leave this open at least until @jpalus is clear of the issue.

**Comment by lemire** [comment] 2021-01-07 16:14
At the rate we are going, release 0.8 should come soon enough.

**Comment by jpalus** [comment] 2021-01-07 16:38
I must be doing something really wrong :).

To confirm that compiled code actually works in practice I went back to my real world use case (tried example just to confirm issue with strings is the same as mine) but I'm still struggling to get expected result. This might be another issue... or my misunderstanding. Let me know if I should raise another ticket.

The input is array of objects but I cannot figure out how to iterate over objects:
```cpp
  ondemand::document tree = parser.iterate(input);
  for (ondemand::object output : tree) {
```
No iteration happens. I've tried adding get_array():
```cpp
  for (ondemand::object output : tree.get_array()) {
```
but that did nothing.

I've also tried changing `tree` from `document` to `array` but that results in compilation error.

As a last resort I've tried master but both issues are still there
* `for (auto output : tree)` still results in compilation failure
* iteration over array results in nothing

**Comment by jkeiser** [comment] 2021-01-07 16:44
*facepalm* I haven't updated simdjson.h/simdjson.cpp in master. Your code is correct.

One moment, I'll get them updated, and I'll also make sure the exact code at the top compiles and runs correctly against it.

**Comment by jkeiser** [comment] 2021-01-07 16:51
@jpalus OK, please re-download simdjson.h and simdjson.cpp from master, and try again. The code from your original post, up top, compiles and runs correctly for me, at least.

**Comment by jkeiser** [comment] 2021-01-07 16:52
If you're having the issue with different input / code, post your full example and I'll take a look.

**Comment by jkeiser** [comment] 2021-01-07 17:15
@jpalus here's the code I just tried:

```c++
#include "simdjson.h"
using namespace std;
using namespace simdjson::builtin;
int main(void) {
  ondemand::parser parser;
  auto input = R"(
    [
      { "x": 1, "y": 2 },
      { "x": 3, "y": 4 }
    ]
  )"_padded;
  ondemand::document tree = parser.iterate(input);
  for (ondemand::object output : tree) {
    cout << double(output["x"]) << ", " << double(output["y"]) << endl;
  }
}
```

```
g++ -march=native -o test test.cpp simdjson.cpp && ./blah
1, 2
3, 4
```

**Comment by jkeiser** [comment] 2021-01-07 17:16
Note: the above appears to work against 0.7.1 too.

**Comment by jpalus** [comment] 2021-01-07 17:18
Situation somewhat improved but my code still doesn't work as expected, again might be my fault.

First of all `for (auto ` seems to be fine now. That's good.

If I load input from file everything works fine too.

However in my use case I load input from `string_view` and that does not seem to work. See following example with loading same JSON from both string_view and file -- I would expect same outcome:
```cpp
#include "simdjson.h"
using namespace std;
using namespace simdjson;
using namespace simdjson::builtin; // for ondemand
int main(void) {
  ondemand::parser parser;
  string_view from_mem = string_view("[{\"name\":\"test\"}]");
  ondemand::document mem_tree = parser.iterate(from_mem);
  cout << "mem:\n";
  for (auto output : mem_tree) {
    std::string_view name        = output["name"];
    cout << name << endl;
  }
  padded_string from_file = padded_string::load("test.json");
  ondemand::document file_tree = parser.iterate(from_file);
  cout << "file:\n";
  for (auto output : file_tree) {
    std::string_view name        = output["name"];
    cout << name << endl;
  }
}
```
test.json:
```json
[{"name":"test"}]
``` 
Outcome with master:
```
mem:
file:
test
```

Not sure if I'm allowed to load directly from string_view (passes compilation) or am I expected to do some other conversion to padded_string.

**Comment by jkeiser** [comment] 2021-01-07 17:29
Hmm, it's weird that it lets you do that. It was converting from string_view to padded_string in a temporary, and then freeing the padded_string before you iterated, which means the iteration was accessing memory you didn't own.

You need to do `padded_string from_mem = string_view("[{\"name\":\"test\"}]");` (or better yet, `auto from_mem = "[{\"name\":\"test\"}]"_padded`).

I'll fix things up so that what you were doing doesn't compile, but the above should get you fixed.

**Comment by jpalus** [comment] 2021-01-07 17:31
Yep in the meantime confirmed that creating padded_string instead of string_view fixes the problem. Thanks! Looking forward to 0.8.0 release!

**Comment by jkeiser** [comment] 2021-01-07 17:56
@jpalus also note, I still think you'll have a much better time with master than 0.7.1--even the real issue you just encountered is also in 0.7.1. As far as I know, master is just unequivocally better.

**Comment by jkeiser** [comment] 2021-01-07 17:58
@lemire lol, the issue @jpalus encountered--calling iterate on a temporary padded_string--is the one I wrangled and fixed in the documentation checkin :) So this issue *is* resolved by that checkin.

**Comment by jpalus** [comment] 2021-01-07 18:45
@jkeiser actually I'm using master temporarily now but since the tool I'm writing is used on multiple machines it's way more convenient to just upgrade distribution package after proper release. I do realize it's a current trend to use everything from git (try telling vim plugin people you're using code from tag (if they have tags at all), not from git and they'll claim your setup is "unsupported") or that more and more software is package maintainer hostile (cheers to golang, rust and the like) but I'm one of those old-schoolers who still prefer distribution packages ;)

Probably not the best place to ask such questions as the issue got a little lengthy already but is there any penalty associated with going "back" to field occurring earlier in object than one that was requested last time? I'm dealing with JSON in which exact type of object is determined primarily by content of set of fields (in non-trivial way). So I'm wondering whether it's worth to push for code reorganization to never go back or perhaps there is a place for "find_field" method which accepts multiple fields and returns first encountered?

**Comment by lemire** [comment] 2021-01-07 19:45
> I do realize it's a current trend to use everything from git or that more and more software is package maintainer hostile (cheers to golang, rust and the like) but I'm one of those old-schoolers who still prefer distribution packages ;)

I would never, ever, recommend that you design production code from the tip of our main branch. We issue releases which you can download as zip/tar files. That is what you should work from, if you want to build software in real systems.


> So I'm wondering whether it's worth to push for code reorganization to never go back or perhaps there is a place for "find_field" method which accepts multiple fields and returns first encountered?

There might be benefits to an API where you just throw the fields you want, sort of like a regular expression matcher. I will open an issue.

I very much doubt that we will have this feature in the near future (i.e., it won't be there next week).

**Comment by lemire** [comment] 2021-01-07 19:54
@jpalus I have opened an issue: https://github.com/simdjson/simdjson/issues/1382

**Comment by jkeiser** [comment] 2021-01-07 21:35
> @jkeiser actually I'm using master temporarily now but since the tool I'm writing is used on multiple machines it's way more convenient to just upgrade distribution package after proper release. I do realize it's a current trend to use everything from git (try telling vim plugin people you're using code from tag (if they have tags at all), not from git and they'll claim your setup is "unsupported") or that more and more software is package maintainer hostile (cheers to golang, rust and the like) but I'm one of those old-schoolers who still prefer distribution packages ;)

Agreed with @lemire, we don't really want people to stay on master all the time. I just think there are enough improvements to this alpha feature that you'll have an easier time using master while you learn. It doesn't hurt than 0.8 is right around the corner.

> Probably not the best place to ask such questions as the issue got a little lengthy already but is there any penalty associated with going "back" to field occurring earlier in object than one that was requested last time? I'm dealing with JSON in which exact type of object is determined primarily by content of set of fields (in non-trivial way).

In 0.7.1, it's *impossible* to go back, making optional fields kinda hard to deal with. This is fixed in master (part of the reason I recommend it). There is a performance penalty (it scans through the entire object each time you miss a field, but if your objects aren't huge, or you can design it so that you *mostly* go forward, you should be in good shape.

> So I'm wondering whether it's worth to push for code reorganization to never go back

If you have a massive amount of out of order / optional fields, and have huge objects, right now your best bet is to iterate through the object with something like:

```c++
for (auto field : object.get_object()) {
  double x, y, z;
  if (field.key() == "x") { x = field.value(); }
  else if (field.key() == "y") { y = field.value(); }
  else if (field.key() == "z") { z = field.value(); }
}
```

I'm working from memory and haven't compiled that, so YYMV, but it feels about right to me.

**I wouldn't do the above unless I was absolutely forced to, though :)** It's so much less straightforward (and harder to read) than just using ["x/y/z"].

> or perhaps there is a place for "find_field" method which accepts multiple fields and returns first encountered?

Echoing @lemire that a feature which lets you specify the set of fields you want would be super nice. I'd love it to work in a sort of xpath/jsonpath-y fashion, even. We're trying to get the underlying interface rock solid, performant and effortless to work with before we build some of that, though. So probably not for 1.0 :)

**Closed** 2021-01-09 21:34 UTC
Labels: bug, documentation
