### ISSUE TITLE
C++20 build warnings

### ISSUE THREAD

**Issue by ivan-volnov** [simdjson/simdjson#1782] opened 2022-01-16 14:58 UTC
Hi there!

I hope you are fine during these days.

I got a bunch of warnings during compilation using clang 13 with C++20 standard.

```
simdjson/include/simdjson/haswell/simd.h:268:115: warning: ISO C++20 considers use of overloaded operator '==' (with operand types 'simd8<uint8_t>' (aka 'simd8<unsigned char>') and 'const simd8<uint8_t>' (aka 'const simd8<unsigned char>')) to be ambiguous despite there being a unique best viable function [-Wambiguous-reversed-operator]
    simdjson_really_inline simd8<bool> operator<=(const simd8<uint8_t> other) const { return other.max_val(*this) == other; }
                                                                                             ~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~
simdjson/include/simdjson/haswell/simd.h:48:33: note: ambiguity is between a regular call to this operator and a call with the argument order reversed
    simdjson_really_inline Mask operator==(const simd8<T> other) const { return _mm256_cmpeq_epi8(*this, other); }
                                ^
simdjson/include/simdjson/haswell/simd.h:269:115: warning: ISO C++20 considers use of overloaded operator '==' (with operand types 'simd8<uint8_t>' (aka 'simd8<unsigned char>') and 'const simd8<uint8_t>' (aka 'const simd8<unsigned char>')) to be ambiguous despite there being a unique best viable function [-Wambiguous-reversed-operator]
    simdjson_really_inline simd8<bool> operator>=(const simd8<uint8_t> other) const { return other.min_val(*this) == other; }
                                                                                             ~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~
simdjson/include/simdjson/haswell/simd.h:48:33: note: ambiguity is between a regular call to this operator and a call with the argument order reversed
    simdjson_really_inline Mask operator==(const simd8<T> other) const { return _mm256_cmpeq_epi8(*this, other); }
...
simdjson/include/simdjson/westmere/simd.h:238:115: warning: ISO C++20 considers use of overloaded operator '==' (with operand types 'simd8<uint8_t>' (aka 'simd8<unsigned char>') and 'const simd8<uint8_t>' (aka 'const simd8<unsigned char>')) to be ambiguous despite there being a unique best viable function [-Wambiguous-reversed-operator]
    simdjson_really_inline simd8<bool> operator<=(const simd8<uint8_t> other) const { return other.max_val(*this) == other; }
                                                                                             ~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~
simdjson/include/simdjson/westmere/simd.h:47:33: note: ambiguity is between a regular call to this operator and a call with the argument order reversed
    simdjson_really_inline Mask operator==(const simd8<T> other) const { return _mm_cmpeq_epi8(*this, other); }
                                ^
simdjson/include/simdjson/westmere/simd.h:239:115: warning: ISO C++20 considers use of overloaded operator '==' (with operand types 'simd8<uint8_t>' (aka 'simd8<unsigned char>') and 'const simd8<uint8_t>' (aka 'const simd8<unsigned char>')) to be ambiguous despite there being a unique best viable function [-Wambiguous-reversed-operator]
    simdjson_really_inline simd8<bool> operator>=(const simd8<uint8_t> other) const { return other.min_val(*this) == other; }
                                                                                             ~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~
simdjson/include/simdjson/westmere/simd.h:47:33: note: ambiguity is between a regular call to this operator and a call with the argument order reversed
    simdjson_really_inline Mask operator==(const simd8<T> other) const { return _mm_cmpeq_epi8(*this, other); }
```

These warnings are from rev 714f0ba2226cf996fdd575f8c0e7a3c092c194bd, but on master is the same.

**Comment by lemire** [comment] 2022-01-16 16:31
Yes. I am aware. If someone can help me understand and fix these warnings, that would be great.

**Comment by ivan-volnov** [comment] 2022-01-19 15:52
There are more warnings connected to this issue:

```
simdjson/include/simdjson/haswell/simd.h:346:25: warning: ISO C++20 considers use of overloaded operator '==' (with operand types 'const simd8<unsigned char>' and 'const simd8<unsigned char>') to be ambiguous despite there being a unique best viable function [-Wambiguous-reversed-operator]
        this->chunks[0] == other.chunks[0],
        ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~
simdjson/src/haswell/dom_parser_implementation.cpp:68:34: note: in instantiation of member function 'simdjson::haswell::(anonymous namespace)::simd::simd8x64<unsigned char>::eq' requested here
  const uint64_t whitespace = in.eq({
                                 ^
simdjson/include/simdjson/haswell/simd.h:48:33: note: ambiguity is between a regular call to this operator and a call with the argument order reversed
    simdjson_really_inline Mask operator==(const simd8<T> other) const { return _mm256_cmpeq_epi8(*this, other); }
                                ^
simdjson/include/simdjson/haswell/simd.h:347:25: warning: ISO C++20 considers use of overloaded operator '==' (with operand types 'const simd8<unsigned char>' and 'const simd8<unsigned char>') to be ambiguous despite there being a unique best viable function [-Wambiguous-reversed-operator]
        this->chunks[1] == other.chunks[1]
        ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~
simdjson/include/simdjson/haswell/simd.h:48:33: note: ambiguity is between a regular call to this operator and a call with the argument order reversed
    simdjson_really_inline Mask operator==(const simd8<T> other) const { return _mm256_cmpeq_epi8(*this, other); }
                                ^
simdjson/include/simdjson/haswell/simd.h:339:25: warning: ISO C++20 considers use of overloaded operator '==' (with operand types 'const simd8<unsigned char>' and 'const simd8<unsigned char>') to be ambiguous despite there being a unique best viable function [-Wambiguous-reversed-operator]
        this->chunks[0] == mask,
        ~~~~~~~~~~~~~~~ ^  ~~~~
simdjson/src/generic/stage1/json_string_scanner.h:111:33: note: in instantiation of member function 'simdjson::haswell::(anonymous namespace)::simd::simd8x64<unsigned char>::eq' requested here
  const uint64_t backslash = in.eq('\\');
                                ^
simdjson/include/simdjson/haswell/simd.h:48:33: note: ambiguity is between a regular call to this operator and a call with the argument order reversed
    simdjson_really_inline Mask operator==(const simd8<T> other) const { return _mm256_cmpeq_epi8(*this, other); }
                                ^
simdjson/include/simdjson/haswell/simd.h:340:25: warning: ISO C++20 considers use of overloaded operator '==' (with operand types 'const simd8<unsigned char>' and 'const simd8<unsigned char>') to be ambiguous despite there being a unique best viable function [-Wambiguous-reversed-operator]
        this->chunks[1] == mask
        ~~~~~~~~~~~~~~~ ^  ~~~~
simdjson/include/simdjson/haswell/simd.h:48:33: note: ambiguity is between a regular call to this operator and a call with the argument order reversed
    simdjson_really_inline Mask operator==(const simd8<T> other) const { return _mm256_cmpeq_epi8(*this, other); }
```

Hope it can help somehow.

**Comment by lemire** [comment] 2022-01-19 16:35
I know what the warnings are. I don't know why clang emits the warnings and I do not know how to fix them.

That's why I am asking for help. I need someone to dig into it and finds out what the issue is. At the very least. Then we might have a chance to fix the warnings.

**Comment by ivan-volnov** [comment] 2022-01-19 17:08
Yes I understand. Tried two times, but simd.h is a kind of a dark magic for a person who doesn't know the code well. So, that two times I failed to fix it in a time frame I defined for it.
I hope the library authors should have some clue about the warning.

**Comment by lemire** [comment] 2022-01-19 17:20
I am one of the library authors. There is no magic involved. These are templates with overloaded equality operators. It is standard C++.

The error suggests that there is something ambiguous. I am sure there is, but finding out where the ambiguity lies is the key.

This should not require any in-depth knowledge of the simdjson library.

**Comment by jkeiser** [comment] 2022-01-20 00:50
I looked into this issue a while back, and find it had to do with changes to how c++20 works with overloaded operators. I can't remember if I had a solution, but I think I didn't.

**Comment by jkeiser** [comment] 2022-01-20 00:53
#748 is where we first encountered this.

**Comment by lemire** [comment] 2022-01-20 02:56
Right. I see this. I still do not understand the warnings.

**Comment by jkeiser** [comment] 2022-01-20 04:13
They boiled the issue down further here, but haven't fixed it yet: https://github.com/boostorg/date_time/issues/132

**Comment by lemire** [comment] 2022-01-20 14:21
@jkeiser Do you understand the same thing that I do, that we can patch it with something like this...

```diff
-    bool operator==(T const&) const;
+    friend bool operator==(T const&, T const&);
```


@ivan-volnov Would be willing to give it a try with this type of patch and see if it resolves the problem ? If so, we could just merge a simple patch and be done with it. 

Unless the gods hate us, it should be entirely safe to do so. And if it resolves the warnings, then great.

(I still do not understand the underlying issue. I do not see the ambiguity. If someone could explain it to me...)

**Comment by ivan-volnov** [comment] 2022-01-20 15:01
@lemire Thanks for the hint. It works! I'll post a PR.

**Comment by ivan-volnov** [comment] 2022-01-20 15:20
@lemire I also noticed that I build both westmere and haswell files on my PC. Is it normal?

**Comment by lemire** [comment] 2022-01-20 19:06
> I also noticed that I build both westmere and haswell files on my PC. Is it normal?

Yes. Of course. Because we have runtime dispatch.

**Comment by lemire** [comment] 2022-01-20 19:16
Closing. If the issue comes back, please reopen a new issue.

This will be part of the next release.

**Closed** 2022-01-31 16:38 UTC
Labels: bug (unverified)
