### ISSUE TITLE
Option to get number in JSON as string in the DOM API

### ISSUE THREAD

**Issue by michaeleisel** [simdjson/simdjson#425] opened 2019-12-28 22:45 UTC
It would helpful, when an iterator is at an int or double value, to have an option to parse it as a string. This allows the consumer to decide how to do the parsing (it is helpful for me for dealing with the BigInt class https://developer.apple.com/documentation/foundation/decimal ). I can hack up something good enough for myself, but might be useful for others to have an officially supported way

**Comment by lemire** [comment] 2019-12-29 01:56
Yes, we should do this... Sounds reasonable.

**Comment by michaeleisel** [comment] 2019-12-30 15:45
Actually, I'm finding this a bit tricky... is there currently an easy way to get the position in the JSON string from the iterator? All I can find is the location on the tape

**Comment by lemire** [comment] 2019-12-30 15:59
By design, in simdjson, once you have parsed a string, you can effectively discard it and you have (semantically) a copy of the JSON document. In fact, in the upcoming code I am working on, it will even be possible to consume the JSON input string in chunks (e.g., give me 8kB of string, I parse it, give me again 8kB of string, I parse it).

To support what you want in the simdjson requires copying the input number. Effectively, we would treat numbers as strings, possibly after validating them.

**Comment by lemire** [comment] 2020-01-09 18:50
Related https://github.com/lemire/simdjson/issues/167

**Comment by jkeiser** [comment] 2020-01-27 20:52
It would be neat to have a "simdjson lite" that returns (essentially) the stage 1 output, and the user could traverse that, parsing only the keys and values they cared about.

**Comment by jkeiser** [comment] 2020-01-27 21:04
Note that errors are another good reason to want the original string for something. If you are reporting an error, for example (like "number must be between 0 and 100"), printing the original string can help the user find and fix the error in ways that a reinterpreted value can't.  For example, they can eyescan for 4.5000 but not if you write 4.5--or you might be confused to see 1.5e6 when you wrote 1500000. And seeing an unescaped string can be super confusing when your file is all `\u`.

Being able to reconstruct the line/column # is another reason to want values linked to the original JSON (which is one clear way of implementing this).

**Comment by TkTech** [comment] 2020-04-01 10:43
Likewise, this would be nice to have for pysimdjson so users can optionally use the Decimal class for exact precision.

**Comment by lemire** [comment] 2020-04-01 12:53
@jkeiser  This could possibly be achieved as part of the 1.0 milestone, given that it seems a frequently requested feature.

**Comment by lemire** [comment] 2021-07-20 18:29
Note that this is effectively supported now with the On Demand API and documented as such:

```
simdjson::ondemand::parser parser;
simdjson::padded_string docdata =  R"({"value":12321323213213213213213213213211223})"_padded;
simdjson::ondemand::document doc = parser.iterate(docdata);
simdjson::ondemand::object obj = doc.get_object();
std::string_view token = obj["value"].raw_json_token();
```

**Comment by jkeiser** [comment] 2021-08-13 18:18
Since we're deprecating the DOM API, I think we can close this. @michaeleisel please do feel free to reopen if this doesn't work for you, though!

**Closed by jkeiser** 2021-08-13 18:18 UTC
Labels: enhancement

**Comment by TkTech** [comment] 2021-10-04 15:31
Is the DOM API actually being deprecated? This is counter to my understanding. The DOM API is still very much in use and often a better fit than the OnDemand API.

**Comment by lemire** [comment] 2021-10-05 12:17
@TkTech The DOM API is very much going to stay. Everything in the 1.0 release should stay... forever?

What I think @jkeiser meant by "deprecated" is that we now make OnDemand our default and the DOM API is an 'extra'. I should point out that even @jkeiser hacked the DOM code fairly recently... so I don't think he meant that such code would be removed.

If you need a materialized DOM tree, then, obviously, a DOM API is better.

Note that we can and maybe should write an equivalent for the DOM API (I refer to the function in the current issue) but it would evidently be quite different. In On Demand, you can bypass the string serialization and just retrieve directly, say, a double. In DOM, you don't have much choice... you need to serialize a string, and then, from the string, we could offer some option to read directly a number. It would not be difficult to add this functionality.
