### ISSUE TITLE
Lower performance on small files

### ISSUE THREAD

**Issue by plokhotnyuk** [simdjson/simdjson#70] opened 2019-02-25 16:40 UTC
I have checked on small messages with size 10Kb - 15Kb and the benchmark shows only 0.3 - 0.5 Gb per second, while for original files it shows more than 2 Gb per second. 

Also, when messages grow in size up to 10Mb then benchmark shows ~1.5 Gb.

Sources of small files are [here](https://github.com/plokhotnyuk/jsoniter-scala/tree/master/jsoniter-scala-benchmark/src/main/resources/com/github/plokhotnyuk/jsoniter_scala/benchmark). 

Bellow is a full output:
```
andriy@notebook:~/Projects/com/github/lemire/simdjson$ ./parse jsonexamples/jsoniter-scala/che-1.geo.json 
number of bytes 11481 number of structural chars 3310 ratio 0.288
mem alloc instructions:       1346 cycles:       3165 (4.38 %) ins/cycles: 0.43 mis. branches:          2 (cycles/mis.branch 1526.95) cache accesses:        136 (failure          0)
 mem alloc runs at 0.28 cycles per input byte.
stage 1 instructions:      47601 cycles:      14322 (19.80 %) ins/cycles: 3.32 mis. branches:          3 (cycles/mis.branch 4227.40) cache accesses:        136 (failure          0)
 stage 1 runs at 1.25 cycles per input byte.
stage 2 instructions:     190120 cycles:      54860 (75.83 %) ins/cycles: 3.47 mis. branches:        126  (cycles/mis.branch 434.83)  cache accesses:        338 (failure          0)
 stage 2 runs at 4.78 cycles per input byte and 16.57 cycles per structural character.
 all stages: 6.30 cycles per input byte.
Min:  3.7839e-05 bytes read: 11481 Gigabytes/second: 0.303417
andriy@notebook:~/Projects/com/github/lemire/simdjson$ ./parse jsonexamples/jsoniter-scala/twitter_api_response.json 
number of bytes 15253 number of structural chars 1440 ratio 0.094
mem alloc instructions:       1346 cycles:       3010 (10.41 %) ins/cycles: 0.45 mis. branches:          1 (cycles/mis.branch 2886.06) cache accesses:        207 (failure          0)
 mem alloc runs at 0.20 cycles per input byte.
stage 1 instructions:      41378 cycles:      12579 (43.50 %) ins/cycles: 3.29 mis. branches:          1 (cycles/mis.branch 9256.61) cache accesses:        207 (failure          0)
 stage 1 runs at 0.82 cycles per input byte.
stage 2 instructions:      42454 cycles:      13330 (46.09 %) ins/cycles: 3.18 mis. branches:         14  (cycles/mis.branch 930.40)  cache accesses:        294 (failure          0)
 stage 2 runs at 0.87 cycles per input byte and 9.26 cycles per structural character.
 all stages: 1.90 cycles per input byte.
Min:  2.8586e-05 bytes read: 15253 Gigabytes/second: 0.533583
andriy@notebook:~/Projects/com/github/lemire/simdjson$ ./parse jsonexamples/twitter.json
number of bytes 631514 number of structural chars 55264 ratio 0.088
mem alloc instructions:       1191 cycles:        792 (0.07 %) ins/cycles: 1.50 mis. branches:          1 (cycles/mis.branch 616.13) cache accesses:      30067 (failure          0)
 mem alloc runs at 0.00 cycles per input byte.
stage 1 instructions:    1825757 cycles:     575452 (51.51 %) ins/cycles: 3.17 mis. branches:       1506 (cycles/mis.branch 382.07) cache accesses:      30067 (failure         27)
 stage 1 runs at 0.91 cycles per input byte.
stage 2 instructions:    1639867 cycles:     540975 (48.42 %) ins/cycles: 3.03 mis. branches:       1406  (cycles/mis.branch 384.52)  cache accesses:      52092 (failure         50)
 stage 2 runs at 0.86 cycles per input byte and 9.79 cycles per structural character.
 all stages: 1.77 cycles per input byte.
Min:  0.000309023 bytes read: 631514 Gigabytes/second: 2.04358
andriy@notebook:~/Projects/com/github/lemire/simdjson$ ./parse jsonexamples/jsoniter-scala/twitter_api_response_10Mb.json 
number of bytes 9606023 number of structural chars 905350 ratio 0.094
mem alloc instructions:       1443 cycles:       7052 (0.04 %) ins/cycles: 0.20 mis. branches:         13 (cycles/mis.branch 526.28) cache accesses:     337396 (failure        250)
 mem alloc runs at 0.00 cycles per input byte.
stage 1 instructions:   25956521 cycles:    8704923 (48.30 %) ins/cycles: 2.98 mis. branches:      10742 (cycles/mis.branch 810.34) cache accesses:     337396 (failure     237093)
 stage 1 runs at 0.91 cycles per input byte.
stage 2 instructions:   26562775 cycles:    9310078 (51.66 %) ins/cycles: 2.85 mis. branches:       7822  (cycles/mis.branch 1190.20)  cache accesses:     653145 (failure     415533)
 stage 2 runs at 0.97 cycles per input byte and 10.28 cycles per structural character.
 all stages: 1.88 cycles per input byte.
Min:  0.00619737 bytes read: 9606023 Gigabytes/second: 1.55002
```

**Comment by geofflangdale** [comment] 2019-02-25 18:19
I'm not all that surprised that the system doesn't record in the Gigabytes/second range for files that are over that quickly. I wouldn't be startled to see that we have some fixed costs whether in our measurement infrastructure or at startup/teardown. This is worth looking into.

Second, not all JSON files go through our system at the same speed. Notably, number parsing is slower (see the linked paper, which has a regression model of expected costs based on bytes, number of 'structural characters' and number of number values to be scanned).

**Comment by lemire** [comment] 2019-02-25 18:48
We have collected several examples where the speed is less than 1 GB/s (see the big bar chart we post in the README). The paper (https://arxiv.org/pdf/1902.08318.pdf) has more details. Lower speeds are typically related to files that contain lots of numbers (in which cases it becomes a number parsing task) or difficult string normalization (in which case it becomes a string normalization task). 

The file where you get the lowest performance (che-1.geo.json) looks like this...

> (...) [[[7.697223,47.543327],[7.769722,47.553329],[7.906388,47.558052],[7.91361,47.553886],[7.918888,47.552773]
,[7.931944,47.552216],[8.033333,47.556107],[8.086666,47.560555],[8.092222,47.561661],[8.099722,47.565552],[8.102499,47.568329],[8.103888,47.571938],[8.108055,47.578331],[8.110832,47.581108],[8.185276,47.617218],[8.193333,47.620827],[
8.198889,47.621666],[8.205555,47.621666],[8.240833,47.619438],[8.283333,47.613052],[8.288055,47.611664],[8.2925,47.605827],[8.390833,47.579994] (...)

So it is essentially just a number parsing benchmark. It would be interesting to accelerate number parsing, but this remains an open problem. I think most parsers have more or less the same speed when parsing numbers.

**Comment by lemire** [comment] 2019-02-25 19:02
I have renamed the issue the refer to the fact that we have small files. If there is an issue with large files, it would be interesting to document it separately.

**Comment by lemire** [comment] 2019-02-25 19:03
Future work should example more carefully small files.

**Comment by lemire** [comment] 2019-03-01 22:40
Note that with small files, it becomes important to reuse the `ParsedJson` objects. That is, you don't want to constantly allocate and de-allocate memory... I don't think it plays a role in the benchmarks above, but in an actual application, it would matter.

**Comment by Raincode** [comment] 2019-03-13 17:52
Once compiler vendors properly support the C++17 standard, you will have std::from_chars, maybe? AFAIK this should be pretty fast for parsing numbers, but atm only integers are supported e.g. on GCC.

**Comment by lemire** [comment] 2019-03-13 18:39
@Raincode Why would you expect `from_chars` to be faster that our current approach?

Note that we have to follow the JSON spec. This may or may not be possible using `from_chars`.

**Comment by Raincode** [comment] 2019-03-15 15:14
> @Raincode Why would you expect `from_chars` to be faster that our current approach?

That's not necessarily what I meant (you can only find out by testing it). Just wanted to bring up a possible alternative solution (if it is ever supported properly).
> not sure that will actually be faster than what you have in place atm.

---

> Note that we have to follow the JSON spec

That's something I didn't consider, not sure how JSON spec differs e.g. with overflows etc.

**Comment by lemire** [comment] 2020-03-27 20:41
I am going to close this issue. It is nothing to do with small files in retrospect. The files where we get low performance are number parsing stress tests.

We recently added the following remark to our README:

> Many files are mostly made of numbers: canada, mesh.pretty, mesh, random and numbers: in such instances, we see lower JSON parsing speeds due to the high cost of number parsing. The simdjson library uses exact number parsing which is particular taxing.

I am also not preoccupied by our performance now that we have exact parsing in master...

```
$ for i in *.json ; do echo $i; ./parsingcompetition $i  ; done
che-1.geo.json
simdjson                                	:    4.841 cycles per input byte (best)    4.880 cycles per input byte (avg)    0.689 GB/s (error margin: 0.005 GB/s)
RapidJSON (accurate number parsing)     	:   18.326 cycles per input byte (best)   19.185 cycles per input byte (avg)    0.185 GB/s (error margin: 0.008 GB/s)
RapidJSON (insitu, accurate number parsing)	:   18.158 cycles per input byte (best)   18.957 cycles per input byte (avg)    0.187 GB/s (error margin: 0.008 GB/s)
nlohmann-json                           	:   90.423 cycles per input byte (best)   91.077 cycles per input byte (avg)    0.038 GB/s (error margin: 0.000 GB/s)

che-2.geo.json
simdjson                                	:    4.849 cycles per input byte (best)    4.882 cycles per input byte (avg)    0.687 GB/s (error margin: 0.005 GB/s)
RapidJSON (accurate number parsing)     	:   18.248 cycles per input byte (best)   19.197 cycles per input byte (avg)    0.186 GB/s (error margin: 0.009 GB/s)
RapidJSON (insitu, accurate number parsing)	:   18.178 cycles per input byte (best)   18.951 cycles per input byte (avg)    0.186 GB/s (error margin: 0.008 GB/s)
nlohmann-json                           	:   91.483 cycles per input byte (best)   91.842 cycles per input byte (avg)    0.037 GB/s (error margin: 0.000 GB/s)

che-3.geo.json
simdjson                                	:    4.862 cycles per input byte (best)    4.892 cycles per input byte (avg)    0.686 GB/s (error margin: 0.004 GB/s)
RapidJSON (accurate number parsing)     	:   18.316 cycles per input byte (best)   19.202 cycles per input byte (avg)    0.185 GB/s (error margin: 0.008 GB/s)
RapidJSON (insitu, accurate number parsing)	:   18.143 cycles per input byte (best)   18.957 cycles per input byte (avg)    0.187 GB/s (error margin: 0.008 GB/s)
nlohmann-json                           	:   91.462 cycles per input byte (best)   91.758 cycles per input byte (avg)    0.037 GB/s (error margin: 0.000 GB/s)


google_maps_api_compact_response.json
getline                                 	:    0.209 cycles per input byte (best)    0.212 cycles per input byte (avg)   10.867 GB/s (error margin: 0.180 GB/s)
simdjson (dynamic mem)                  	:    4.226 cycles per input byte (best)    4.295 cycles per input byte (avg)    0.786 GB/s (error margin: 0.013 GB/s)
simdjson                                	:    2.684 cycles per input byte (best)    2.726 cycles per input byte (avg)    1.221 GB/s (error margin: 0.018 GB/s)
RapidJSON                               	:   17.362 cycles per input byte (best)   18.073 cycles per input byte (avg)    0.195 GB/s (error margin: 0.008 GB/s)
```

For the other files, I get upward of 1 GB/s.

I'd really like to be parsing numbers at gigabytes per second... I don't think it is going to be possible in general using a single core.

If someone has any other points to raise, I'll be glad to reopen this issue, but I think we have explored it well. We have documented how we do well even on small files. We have much improved our number parsing performance... but we are just not going to be parsing numbers at 2GB/s... a few hundred MB/s is all you can hope for in general.

@plokhotnyuk : Thanks for raising this issue. This was very fruitful.

**Closed by lemire** 2020-03-27 20:41 UTC
Labels: enhancement, help wanted

**Comment by plokhotnyuk** [comment] 2020-03-27 20:58
@lemire I'm happy that it helped!

Will you open a separate issue for big files or it is already fixed?

**Comment by lemire** [comment] 2020-03-27 21:14
@plokhotnyuk  

I have opened a PR for documenting the resolution of this issue, see https://github.com/simdjson/simdjson/pull/638

**Comment by lemire** [comment] 2020-03-27 23:09
> Will you open a separate issue for big files or it is already fixed?

This is largely resolved: the problem with large files (tens or hundreds of megabytes) has to do with the cost of memory allocation... On some systems, memory allocations can be under 2 GB/s which stalls the parsing. 

https://github.com/simdjson/simdjson/blob/master/doc/performance.md#large-files-and-huge-page-support

So if you either amortize the cost (by parsing several large files) or you use huge/large pages, you will be fine.

Long term, we want to work on reducing effective memory usages for large files and support a SAX-like API.

We also have a threaded (multicore) streaming API if you have one large file made of several JSON documents in sequence:  `parser.parse_many`.
