### ISSUE TITLE
check if a specific key exists in the json string

### ISSUE THREAD

**Issue by tickox** [simdjson/simdjson#1502] opened 2021-03-16 09:33 UTC
Hello,

Is there a way to check if a specific key exists in the json string?
I receive json messages that I have to send to different functions depending on the different fields and certain messages
should just be ignored if a specific key does not exist.

Here is an example of json:

{"table": "orderBookL2_25", "action": "update", "data": [{"symbol": "XBTUSD", "id": 8794415000, "side": "Buy", "size": 225499 }]}

For example, if the json doesn't contain "table", I don't process it at all.
If it exists, I have to pass the "data" field to another function to process it etc.

Thank you

**Comment by lemire** [comment] 2021-03-16 14:44
Something like this maybe ?

```C++
#include "simdjson.h"
using namespace std;
using namespace simdjson;
int main(void) {
  ondemand::parser parser;
  padded_string json =
      R"({"table": "orderBookL2_25", "action": "update", "data": [{"symbol": "XBTUSD", "id": 8794415000, "side": "Buy", "size": 225499 }]})"_padded;
  ondemand::document doc = parser.iterate(json);
  auto result = doc.get_object().find_field("table");
  if (result.error() == SUCCESS) {
    std::cout << "table key found" << std::endl;
  }
}
```

You may need to elaborate.

**Comment by tickox** [comment] 2021-03-16 20:22
Hello, 

Thank you, I had found this solution but I was asking if there was another way to do it.
Am I doing something wrong to process the json string?
I have better performance with nolhaman json.

Here is a small example :

```cpp
ondemand::parser parser_;

void on_message(const std::shared_ptr<WssClient::Connection>& connection,
                const std::shared_ptr<WssClient::InMessage>& in_message) {
  auto json = padded_string(in_message->string());
  auto doc = parser_.iterate(json);
  std::string_view res;
  auto result = doc["table"].get(res);
  if (result == SUCCESS) {
    std::string_view res = doc["table"];
    if (res == "orderBookL2_25") {
      handle_orderbook(doc);
    } else if (res == "instrument") {
      handle_price(doc);
    } else if (res == "trade") {
      handle_trade(doc);
    }
  }
}

template <typename T>
void handle_price(T& message) {
  Timer tt;
  std::string_view type = message["action"];
  if (type == "update") {
    for (auto i : message["data"]) {
      price_t price;
      auto error = i["lastPrice"].get(price);
      if (!error) {
        MessageLastPrice<price_t> m;
        m.symbol = i["symbol"];
        m.broker = "Bitmex";
        m.price = price;
        m.event_time = EpochConverter(i["timestamp"]);
        mes_.notify(m);
        spdlog::info("Performance -> {} microseconds", tt.elapsed());
        return;
      }
    }
  }
}
```

**Comment by lemire** [comment] 2021-03-16 21:05
@tickox 

You want to avoid doing the following...

```
auto json = padded_string(in_message->string());
```

This will call a `new []` followed by a `delete[]` each and every time. If your code is in a tight loop, you want to avoid memory allocation.

**Comment by lemire** [comment] 2021-03-16 21:41
@tickox Ideally, you'd be passing a `std::string_view` instance.

See...

https://lemire.me/blog/2020/08/08/performance-tip-constructing-many-non-trivial-objects-is-slow/

Generating many `std::string` instances is convenient but it is not fast. You want to allocate a fixed buffer (as much as possible) and write there, and then pass `std::string_view` instances.

**Comment by lemire** [comment] 2021-03-16 21:52
We recommend against creating many `std::string` or `simdjson::padded_string` instances to store the JSON content in your application. [Creating many non-trivial objects is convenient but often surprisingly slow](https://lemire.me/blog/2020/08/08/performance-tip-constructing-many-non-trivial-objects-is-slow/). Instead, as much as possible, you should allocate (once or a few times) reusable memory buffers where you write your JSON content. If you have a buffer `json_str` (of type `char*`) allocated for  `capacity` bytes and you store a JSON document spanning `length` bytes, you can pass it to simdjson as follows:

```c++
 auto doc = parser.iterate(padded_string_view(json_str, length, capacity));
```

**Comment by tickox** [comment] 2021-03-16 22:29
I use this websocket library : https://gitlab.com/eidheim/Simple-WebSocket-Server
Unfortunately, there is no char * and I don't have the knowledge to modify it properly

**Comment by lemire** [comment] 2021-03-16 23:17
I am going to close this issue since I believe that the answer has been provided.

If you have performance concerns, please create a new issue with a reproducible benchmark we can look at (not involving other librairies). To understand performance issues, it is critical to segment the problem. Do not begin with complex code. Start up with simple benchmarks and work your way up.

If you are facing limitations with the other librairies you are using, please report your issues with them.

**Closed by lemire** 2021-03-16 23:17 UTC

**Comment by jkeiser** [comment] 2021-03-17 02:53
@tickox if the library you are using gives you a string, you can use the reserve() method in it to add some padding to the end, which may or may not cause a new / delete.

I'm curious how slow this is going ... are these small documents or large?

**Comment by tickox** [comment] 2021-03-17 08:14
@lemire Yes I understood that my problem is caused by padded_string(in_message->string());
My benchmark is quite complex as it measures the processing time of the message from A to Z.
Basically, the message takes between 2 and 5 microseconds longer to be processed with your library.

@jkeiser I'll try to do that, it's globally only small messages like the ones I put in example.

Thanks for your help.

**Comment by jkeiser** [comment] 2021-03-17 14:29
It baffles me how many libraries--even supposedly performance-conscious ones--force.frequrnt allocations by returning std::string. In this case, the library actually has a buffer underneath that generally *has* the padding, too.

**Comment by lemire** [comment] 2021-03-17 15:03
@jkeiser In this instance, the copy is just something that makes me cringe because the first thing I would do in a service function like that one is to make all memory allocations exceptional. This would be true in all programming languages and with all libraries. 

If @tickox has performance issues, it is almost surely not caused by the copy which is going to be dirt cheap compared to everything else that might happen.

But it is just not possible to assess performance by looking at partial code samples. You need actual benchmarks. People who care about performance need to write good benchmarks, there is just no way around that.

Regarding the larger issue...  C++ code is often not geared toward performance. And that is from the ground up. The iostream is terrible. Often STL can be terrible (by design) performance-wise. The `std::string` is also an issue. It is maybe hard to appreciate it today, but if you go back 20 years, the move to C++ was a move to something "higher level". The appeal of C++ wasn't performance, it was programmer's productivity. It was meant to be a more accessible way to program compared to C. The net result is that people building systems in Java could often make them more performant than the C++ counterpart. This sounds crazy but it is just a fact. And we have an example right here of how it might happen, with lots and lots of dynamic heap allocation in C++ (the Java counterpart would be faster in this respect). This is changing in the sense that C++ is giving us more performance options. Even so, `string_view` was only added recently to C++. I'd be pessimistic regarding C++, but if you look at the evolution of the language (C++20 and friends), it is clear that lots of smart C++ people are taking performance seriously today.

**Comment by tickox** [comment] 2021-03-17 20:33
Thanks for your feedback

@jkeiser After several tests, allocating memory with reserve to avoid dynamic allocation does not change anything.
I managed to pass the buffer to ```char *``` and ```std::string_view```, the ```std::string_view``` has a better performance.

I have one last question to finish.

When I do : ```auto json = padded_string(in_message->to_string_view());```
Is there a dynamic allocation with padded_string?

@lemire So the problem is not C++ but the way it is used, right?

**Comment by lemire** [comment] 2021-03-17 21:23
> `auto json = padded_string(in_message->to_string_view());`

Absolutely. Of course, that's better than first copying to a string and then copying again to a padded_string (two copies).

It is almost surely unnecessary because you can always make it so that the underlying buffer has extra capacity. Just set prepare(n + SIMDJSON_PADDING) and check that you are occupying no more than n characters (you can rely on the storage to be contiguous). Then you will want to use a padded_string_view.

> So the problem is not C++ but the way it is used, right?

You can do high-performance programming in almost any programming language. Of course, the language will set some limitations but within these limitations, there is much you can do. Conversely, you can be slow in every programming language. And, yes, you can easily write really slow C++ code.

I bet that GTA is written in C++, yet it can be terribly inefficient...
https://www.theverge.com/2021/3/15/22332421/grand-theft-auto-online-slow-load-times-fan-made-patch



That is terrible !!! If you are going to write slow code... why on Earth would you choose C++? And I think that the C++ community is coming to grip with this realization.

If you are going to write a slow video game, please use C#. (Note that C# is that slow, but it is at least easier than C++.)

There are clear hints in C++ that performance is not going to be great such as the use of streams. C++ streams are a fine abstraction *if* you do not care for performance. It is, of course, possible to do high-performance streams but most code using streams is slow.

There is a logic to all of this... because being correct and easy to debug is more important than being fast... but the ultimate goal of a great programmer is to produce code that is correct, easy to debug and fast. C++ can definitively achieve at least two of these (correct and fast).

**Comment by tickox** [comment] 2021-03-17 21:40
It is especially that almost all languages have libraries written in C/C++ that allow them to make to make fast code (hello python)

I had seen this story about GTA but I think it's a special case, a studio making millions
with very high level engineers that keeps such a big problem visible to everyone shows a lack of seriousness. I don't even see how it's possible.

All this shows that C++ is a very powerful language but to write optimized code
you really have to understand what's going on under the hood and not use functions/types because they are easy to use.

**Comment by jkeiser** [comment] 2021-03-17 23:22
Note: in case it wasn't clear, the padding bytes at the end of the buffet can contain anything--they just need to be valid memory. simdjson won't modify them either (it can't, it's passed in as const).

**Comment by tickox** [comment] 2021-03-18 15:59
Oh ok thanks ^^
