### ISSUE TITLE
Java-version of the project planned?

### ISSUE THREAD

**Issue by JohannesLichtenberger** [simdjson/simdjson#1725] opened 2021-10-05 09:13 UTC
Do you have any plans to port the project to Java? Maybe it's possible with the new Vector API :-)

**Comment by lemire** [comment] 2021-10-05 12:23
Duplicate of https://github.com/simdjson/simdjson/issues/121

**Closed by lemire** 2021-10-05 12:23 UTC

**Comment by saudet** [comment] 2021-10-06 06:24
@JohannesLichtenberger BTW, it shouldn't be too hard to get this working with JavaCPP, see https://github.com/bytedeco/javacpp-presets/issues/931.
