### ISSUE TITLE
Can't compile in VS2019 with exceptions disabled

### ISSUE THREAD

**Issue by jeremyong** [simdjson/simdjson#1255] opened 2020-10-26 08:17 UTC
`_HAS_EXCEPTIONS=0` is *required* when linking to the STL with exceptions disabled. Currently, headers like `ostream` are included without this compiler definition, even when `SIMDJSON_EXCEPTIONS` is `OFF`. Furthermore, the library internally defines `Wx` so warnings emitted due to unwind semantics being unspecified (when `EHsc` is not supplied as a command line argument) end up error-ing the build.

How is the library intended to be used with MSVC if exceptions are disabled?

Thanks

**Comment by lemire** [comment] 2020-10-26 13:21
I think that's a duplicate of existing issues:

* https://github.com/simdjson/simdjson/issues/807
* https://github.com/simdjson/simdjson/issues/813

> How is the library intended to be used with MSVC if exceptions are disabled?

I do not know. Can you help?

I have not personally investigated this issue at all. Is it as simple as defining `_HAS_EXCEPTIONS=0` when `SIMDJSON_EXCEPTIONS` is `OFF`? In which case, we can easily do it.

I honestly don't know what `EHsc` is.

**Comment by jeremyong** [comment] 2020-10-26 14:35
Yup should be as simple as enabling that define. I can see about opening a
PR later today.

**Comment by lemire** [comment] 2020-10-26 14:46
> Yup should be as simple as enabling that define. I can see about opening a PR later today.

That would be great. If you can tweak our CIs so that they check that it works, it would be even better...

https://github.com/simdjson/simdjson/blob/master/.appveyor.yml
https://github.com/simdjson/simdjson/blob/master/.github/workflows/vs16-ci.yml

**Comment by jeremyong** [comment] 2020-10-26 16:26
I've opened #1256 as an attempt to address this (compiles solution on my machine and tests pass, we'll see how appveyor does).

**Comment by lemire** [comment] 2020-10-26 18:11
Closed via https://github.com/simdjson/simdjson/pull/1256

**Closed by lemire** 2020-10-26 18:11 UTC
Labels: bug (unverified)
