### ISSUE TITLE
-Wassume is triggered in _DEBUG builds with clang-cl

### ISSUE THREAD

**Issue by georgthegreat** [simdjson/simdjson#2207] opened 2024-07-03 10:40 UTC
```
contrib/libs/simdjson/include/simdjson/generic/ondemand/json_iterator-inl.h(393,19): error: the argument to '__assume' has side effects that will be discarded [-Werror,-Wassume]
  SIMDJSON_ASSUME(size_t(depth) < parser->max_depth());
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
contrib/libs/simdjson/include/simdjson/portability.h(186,40): note: expanded from macro 'SIMDJSON_ASSUME'
#define SIMDJSON_ASSUME(COND) __assume(COND)
                                       ^~~~
2 errors generated.
Failed
```
I am not quite sure what are the side effects as I do not see any...

We have not seen it earlier as there is some inconsistency between `NDEBUG`, `_DEBUG` and `SIMDJSON_DEVELOPMENT_CHECKS`, though I can not clearly spell it out.

It looks like `SIMDJSON_ASSUME()` and `SIMDJSON_UNREACHABLE()` should be affected by compiler-specific macros, while `SIMDJSON_DEVELOPMENT_CHECKS` should be affected by `_DEBUG` / `NDEBUG` macros.

**Comment by lemire** [comment] 2024-07-03 12:10
@georgthegreat Can you provide enough details so we can reproduce the issue?

We build with clang-cl in CI:

https://github.com/simdjson/simdjson/blob/master/.github/workflows/vs17-clang-ci.yml

**Comment by georgthegreat** [comment] 2024-07-03 13:06
You have to define `_DEBUG` to reproduce this.
I am not sure how this can be achived in cmake, we use custom build system.

Here is an MSDN page regarding this define:
https://msdn.microsoft.com/en-us/library/abx4dbyh.aspx

**Comment by lemire** [comment] 2024-07-03 13:51
@georgthegreat Thanks! I'll work on this soon.

**Comment by lemire** [comment] 2024-07-04 03:40
Ok. So [Microsoft says](https://learn.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=msvc-170&redirectedfrom=MSDN):



> To build a debug version of your application, the [_DEBUG](https://learn.microsoft.com/en-us/cpp/c-runtime-library/debug?view=msvc-170) flag must be defined and the application must be linked with a debug version of one of these libraries. For more information about using the debug versions of the library files, see [CRT debugging techniques](https://learn.microsoft.com/en-us/cpp/c-runtime-library/crt-debugging-techniques?view=msvc-170).

That is Microsoft specific.

Another relevant macro is `NDEBUG` which stands for `not debug` and it controls whether  `assert` are checked or not. For obvious reasons, if both `NDEBUG` and `_DEBUG` are set, then you are in some state as I do not think you want to build a Debug version of your code (which implies that `_DEBUG` is set when under Visual Studio) while disabling asserts.

Yet another relevant macro is  `_OPTIMIZE_` which is set by some compilers when we are building a release. It is not used, to my knowledge, by Microsoft, and even if it were, you do not expect to ever see `_DEBUG` and `_OPTIMIZE_` to be set.


You tell me that  you are building with `_DEBUG` set. Then you should never get to line 186 in `portability.h` unless you are somehow setting either `NDEBUG` or `_OPTIMIZE_`, but it makes no sense to me that these macros would ever be set in debug mode. So I don't understand how you can get the error you are reporting.

Please see the code:

https://github.com/simdjson/simdjson/blob/5f638951c6b74c7791b0ca4ceaa910898493b54d/include/simdjson/portability.h#L181-L190


So we are clear, we are testing ClangCL under Visual Studio in Debug mode, in CI already. It works fine. It does set `_DEBUG`.

You need to provide us with more information.

**Comment by lemire** [comment] 2024-07-04 03:54
Note that `-Wassume` is a warning, not an error. So it is not an error, it is only a warning that you can ignore.

**Comment by lemire** [comment] 2024-07-04 12:37
I am going to close this as I do not think that there is a bug per se and it is not clear that there is anything we can do better.

If one compiles in debug mode with  `NDEBUG` defined, then one gets a warning about side effects being ignored... but I don't think one should compile in debug mode with `NDEBUG`
 set. Remember that `NDEBUG` tells you that you are not in debug mode, so it is somewhat contradictory.

If the issue is the `__OPTIMIZE__` macro, then it is even more problematic: it should never be set when you are compiling in debug mode. 


In all cases, it is merely a warning that one may silence or ignore.

@georgthegreat If you think there is an actual issue, please open a new issue where you provide a fully reproducible build where this occurs.

**Closed by lemire** 2024-07-04 12:37 UTC

**Comment by georgthegreat** [comment] 2024-07-04 14:31
I am not convinced that the issue is wrong, though you have not given me time to spell out the answer.

We are operating a huge monorepository. Out CI runs test with both optimizations and assertions enabled: this allows us to save a lot of compute quota, as `-O2` optimizes certain cases dramatically. We call this mode `relwithdebinfo` (bad naming alas), but there is also native support in clang for `debug build with optimizations` which is handled by [-Og flag](https://github.com/llvm-mirror/clang/commit/14bfc9e99e6e6903b09480a22c153032be77ae4e).

Why do you think that `__OPTIMIZE__` is in any way bound with `_DEBUG`  / `NDEBUG` at all?

**Comment by georgthegreat** [comment] 2024-07-04 14:34
Another though is: `assume` is a matter of optimization which should be kept in release build: clang can handle these macros and remove / further optimize the code if certain branches are explicitly marker as unreachable.

C++23 adds `[[assume(...)]]` attribute to the standard:
https://en.cppreference.com/w/cpp/language/attributes/assume

**Comment by georgthegreat** [comment] 2024-07-04 14:40
> Note that -Wassume triggers a warning, not an error. To be clear, it is not an error, it is only a warning that you can ignore.

It triggers a warning in the client code, and we build our code with `-Werror`.

**Comment by lemire** [comment] 2024-07-04 21:15
@georgthegreat Try with the latest release. If you still get warnings, people open a new issue.

**Comment by georgthegreat** [comment] 2024-07-04 21:17
I am going to vacation and will be only able to check this in two weeks.
I will check and report the results to this issue.

Thanks a lot for your co-operation!

**Comment by georgthegreat** [comment] 2024-07-05 09:20
@lemire, I was able to test this.
Works just fine, thanks a lot.
