### ISSUE TITLE
Fail to parse string which contains unicode

### ISSUE THREAD

**Issue by lgbo-ustc** [simdjson/simdjson#2288] opened 2024-11-07 11:20 UTC
Before submitting an issue, please ensure that you have read the documentation:

* Basics is an overview of how to use simdjson and its APIs: https://github.com/simdjson/simdjson/blob/master/doc/basics.md
* Performance shows some more advanced scenarios and how to tune for them: https://github.com/simdjson/simdjson/blob/master/doc/performance.md
* Contributing: https://github.com/simdjson/simdjson/blob/master/CONTRIBUTING.md
* We follow the [JSON specification as described by RFC 8259](https://www.rfc-editor.org/rfc/rfc8259.txt) (T. Bray, 2017). If you wish to support features that are not part of RFC 8259, then you should not refer to your issue as a bug.

**Describe the bug**

Cannot parse following string
```
{"deviceId":"431924697b\udff0L\u0001Y"}
```
```
terminate called after throwing an instance of 'simdjson::simdjson_error'
  what():  STRING_ERROR: Problem while parsing a string
```

**Comment by lemire** [comment] 2024-11-07 19:57
Your document is not valid.

You can try parsing it with Python for example:

```
>>> json.loads("""{"deviceId":"431924697b\udff0L\u0001Y"}""")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 26 (char 25)
```

You can still decode it using On Demand and specifying that you want the string to be decoded with replacement, like so:

```C++
#include "simdjson.h"
#include <iostream>

int main(int argc, char *argv[]) {
  simdjson::ondemand::parser parser;
  auto json = R"({"deviceId":"431924697b\udff0L\u0001Y"})"_padded;
  simdjson::ondemand::document doc = parser.iterate(json);
  auto view = doc["deviceId"].get_string(true);
  std::cout << view << std::endl;
  return EXIT_SUCCESS;
}

```

But the problem is upstream. Whoever generated this JSON should be told that it is invalid.

Closing as it works as expected.

**Closed by lemire** 2024-11-07 19:57 UTC
Labels: bug (unverified)

**Comment by lemire** [comment] 2024-11-07 20:00
Please note that it is already fully documented in the On-Demand documentation:

<img width="1060" alt="Screenshot 2024-11-07 at 2 58 35 PM" src="https://github.com/user-attachments/assets/02a68a91-3e12-4010-8620-1900b5048951">

Our DOM API, on the other hand, requires that the input is valid and your example is an invalid input.

**Comment by lgbo-ustc** [comment] 2024-11-08 09:33
We have to use DOM API in our project. I found a option `SIMDJSON_SKIPUTF8VALIDATION`, but it doesn't work on DOM API.

**Comment by lemire** [comment] 2024-11-08 15:19
> We have to use DOM API in our project. I found a option SIMDJSON_SKIPUTF8VALIDATION, but it doesn't work on DOM API. The error is returned at

The document is valid UTF-8, but the string has invalid escape characters. These are distinct concerns.

Just so we are clear and you understand the problem: **your string is not valid Unicode**. The 'true' parameter says 'replace the invalid components of the string'.

When you wrote "Fail to parse string which contains unicode": that is a not a correct representation of the issue. The issue is that the DOM API will trigger an error if a string with **invalid** unicode escape sequences is found.

That is also the standard behaviour in Python.
