### ISSUE TITLE
Mark dom::parser move operations as deleted

### ISSUE THREAD

**Issue by mmatrosov** [simdjson/simdjson#1332] opened 2020-12-07 17:52 UTC
**Describe the bug**
It is possible to move an instance of a `dom::parser`.

**To Reproduce**
Steps to reproduce the behaviour: provide a code sample if possible.

```
  simdjson::dom::parser parser;
  simdjson::dom::element elem = parser.parse("[1, 2, 3]"s);
  auto parser2 = std::move(parser);
  std::cout << elem;
```

Ok, maybe it is not a bug, but it looks like a serious design flaw to me. The only way to access the result of the parse is to store the returned element. But after you move from the parser, the element becomes invalid. And you have no other option to access the parsing result. So what is the point to allow the move then? If you want to reuse the buffer, then I strongly suggest creating a dedicated named function for this purpose.

I experienced this issue while trying to make a wrapper that owns parsing results. It has a parser as a field. And it also stores an element as a result of parsing. But then it turned out defaulted move operations caused the wrapper to become invalid. Probably I'll wrap the parser in a `unique_ptr`, but this behavior was not at all obvious.

**Comment by lemire** [comment] 2020-12-07 18:39
It is a very reasonable point.

I think it is a design issue, and maybe a design error, but I don't think it is a bug since it works "as expected and as documented".

For people reading this, the reason you can move the parser is to reuse it for parsing new documents.

cc @jkeiser

**Comment by jkeiser** [comment] 2020-12-11 19:29
You're right, allowing it right now is unsafe. We should remove that. I'd also like to see the underlying problem preventing a move fixed, but that shouldn't block this.

However, I think we want to make sure people can do things like construct a parser and return it from a method like:

```c++
dom::parser create_parser() {
  dom::parser result;
  result.set_capacity(1024*1024);
  return result;
}

int main(void) {
  dom::parser parser = create_parser();
}
```

In these cases it's *not* unsafe.

**Comment by lemire** [comment] 2020-12-11 20:33
> In these cases it's not unsafe.

Do you know how we could allow this uses but not others?

**Comment by mmatrosov** [comment] 2020-12-11 20:59
Let me share my thoughts. I think you have two options.

## 1. Make it truly movable

IIUC the only thing that prevents `dom::parser` from being truly movable is the inability to access parsed results after the move. So how about allowing this? `dom::parser::parse()` returns `doc.root()`, which seems very much accessible for the subsequent calls. You can explicitly say that returned `dom::element` should be treated as "iterators" with the parser being a "container". Move is an operation that invalidates iterators. This feels very natural and that's how I thought it should have worked when I first touched it.

## 2. Make it truly unmovable

No worries about moves at all in this case. If you want to allow moves for situations like with `create_parser()`, you can always opt-in for moving by wrapping the parser into `unique_ptr`. In this way, those who don't need moves won't pay for extra allocation. But those who need will still be able to do this.

I personally like option 1 a bit more, since it feels more intuitive and because uncopyable and unmovable types might be tricky to deal with. E.g. you cannot put them into `std::vector` or `insert()` them into an associative container.

**Comment by lemire** [comment] 2021-01-22 19:40
I do not think there is agreement on what should be done, so I am moving this to milestone 2.0.

Effectively, right now, you are accessing elements, these elements act as iterators. If you move the parser, they become invalid.

Users may avoid the moves entirely with a unique_ptr. If they do move, they need to be mindful that the elements are invalidated. This is documented.

If someone has ideas on how to make this clearer or easier...

**Comment by mmatrosov** [comment] 2021-01-22 19:53
> Effectively, right now, you are accessing elements, these elements act as iterators. If you move the parser, they become invalid.

That's ok.

> If they do move, they need to be mindful that the elements are invalidated. This is documented.

This is not a problem. The problem is that there is no way to access parsed result after the move was done. How about adding a method like `parser::get_parsed_document()`, which will return the same thing as `parse()`?

**Comment by lemire** [comment] 2021-01-22 20:27
@mmatrosov 

> The problem is that there is no way to access parsed result after the move was done. How about adding a method like parser::get_parsed_document()

You can do `parser2.doc.getroot()`, see my PR where I demonstrate.

**Comment by mmatrosov** [comment] 2021-01-23 19:03
Nice! Could you please elaborate on this line:

> It is not directly documented for good reasons: accessing directly the document is potentially unsafe.

What do you mean by "potentially unsafe"?

**Comment by lemire** [comment] 2021-01-23 20:56
@mmatrosov 

> What do you mean by "potentially unsafe"?

I mean this:

```C++
simdjson::dom::parser parser;
parser.doc.get_root();
```

By giving you access to the internals, we have to trust that you know what you are doing.

**Comment by mmatrosov** [comment] 2021-01-23 22:05
Ok, got it. Well, this is my point: don't make it an "internal". Make it a public well-documented safe function. Add a function `parser::get_parsed_document()` and make it throw an exception, if nothing was parsed yet.

**Comment by lemire** [comment] 2021-01-23 23:04
It sounds good.

Our API support both exceptions and expection-less, so we probably need to return a result instance.

**Comment by mmatrosov** [comment] 2021-01-24 09:00
"we probably need to return a result instance" - sounds logical.

**Comment by lemire** [comment] 2021-01-28 16:20
@mmatrosov I had a closer look. Our document is just a structure with the following state:

```
  std::unique_ptr<uint64_t[]> tape{};
  std::unique_ptr<uint8_t[]> string_buf{};
```

That's all it is.

You are told whether it matches a valid JSON after the parse call. If the parse call succeeds, you are given a pointer within the `tape`. 

In ancient times, the document instance had more flags, including an attribute to indicate whether it represented a valid document or not. The code has since been simplified. Having duplicate flags increases complexity. The contract we have with users is that they are told, during the call to parse, whether it was successful or not, and they are responsible for tracking this information later. The parser instance offers no way to tell whether the last parse was a success irrespective of whether you move it or not. The user is supposed to keep track. Of course, adding a boolean is not hard, but the idea is that we expect the users to what to keep track of successes and failures and we do not want to duplicate this effort.

Could you elaborate on your use case?

So you have a parser instance. You parse a document. At this point, you are given a pointer to the root or maybe it fails. Then you want to move the parser... but, if I understand correctly, you lose track of whether the parser instance has parsed a document successfully previously...

Can you give me an example?

You write...

> I experienced this issue while trying to make a wrapper that owns parsing results. It has a parser as a field. And it also stores an element as a result of parsing. But then it turned out defaulted move operations caused the wrapper to become invalid. Probably I'll wrap the parser in a unique_ptr, but this behavior was not at all obvious.

Shouldn't the wrapper instance that owns parsing results keep track of whether it holds a valid document or not? If it do so, then my proposal can be used safely.

**Comment by lemire** [comment] 2021-01-28 16:39
@mmatrosov E.g., the following should work... (not actually valid code)

```C++
struct my_parser {
  simdjson::dom::parser p{};
  bool is_valid{false};
  
  void parse(padded_string json) {
    if(parser.parse(json).error()) { is_valid=false; } else {is_valid=true; }
  }

  dom::element get_doc() {
   if(is_valid) return parser.doc.root();
   throw myexception("no document!");
  }
}
```

We could even provide such a wrapper if the use case is justified. It is not going to be very difficult code, as you can see.

**Comment by lemire** [comment] 2021-02-01 21:49
Looks like it is a duplicate of https://github.com/simdjson/simdjson/issues/679

**Comment by mmatrosov** [comment] 2021-02-03 10:00
> Looks like it is a duplicate of #679

The referenced issue looks like a superset of the current.

**Comment by mmatrosov** [comment] 2021-02-03 10:05
#1430 is a great fix, thanks a lot!

**Comment by lemire** [comment] 2021-02-04 00:24
@mmatrosov Thank you. It is slow going because we want to be deliberate in how we change the API. It is nice to learn that it meets your needs.

**Comment by mmatrosov** [comment] 2021-02-04 10:22
@lemire I am actually impressed with how fast you react to the created issues and provide fixes :) There are not so many projects with such thorough maintenance. Even among commercial ones (looking at you, Visual Studio), not to say about open source. So I am very delighted to see your engagement and allow me to give you credit for this!

**Closed** 2021-02-10 19:44 UTC
Labels: design issues
