### ISSUE TITLE
singleheader should be below build and .gitignore

### ISSUE THREAD

**Issue by ostri** [simdjson/simdjson#776] opened 2020-04-23 15:56 UTC
The majority of the singleheader folder content is a result of build process.
1. simdjson.?pp and amalgate_demo.cpp files are generated (like binaries), they should not be part of the git contents (gitignore)
2. (maybe) since those files are generated, their place is somewhere below build folder.

**Comment by lemire** [comment] 2020-04-23 16:54
Duplicate of https://github.com/simdjson/simdjson/issues/509

Closing.

**Closed by lemire** 2020-04-23 16:54 UTC

**Comment by jkeiser** [comment] 2020-04-23 19:25
Note: with #784 we will actually be using a generated version in the build. The tricky bit is that we have to update how we release as well as how we give people simdjson.h/cpp from master. The current "download from here" is way easier than "clone, cmake, make and then copy <build_output>/singleheader/*."

**Comment by ostri** [comment] 2020-04-23 19:28
How do you plan to distribute library?

**Comment by lemire** [comment] 2020-04-23 19:39
> How do you plan to distribute library?

The library is part of major linux distributions like [Ubuntu](https://packages.ubuntu.com/source/eoan/simdjson), [Debian](https://packages.debian.org/unstable/source/simdjson), ... It is in [Microsoft vpkg](https://github.com/microsoft/vcpkg/). And it is available as a single-header library as well as a CMake build from the[ GitHub repository](https://github.com/simdjson/simdjson).

**Comment by ostri** [comment] 2020-04-23 19:42
so no libsimdjson.so/a?
single header? if I want to use it I have to download cpp and h. Single header is only h/hpp.
Have I missed something?

**Comment by lemire** [comment] 2020-04-23 20:00
> so no libsimdjson.so/a?

Would you be interested in maintaining prebuilt binaries for various versions of major Linux distributions, freeBSD, macOS and Windows? 

>  I have to download cpp and h. 

That's one way. Under Windows, you can use vpkg. Under Linux, you can pull the package as part of the system (e.g., apt-get install).

> Single header is only h/hpp.

`cat simdjson.h simdjson.cpp > onebigballofcode.h`

then 

`#include  "onebigballofcode.h"`

**Comment by ostri** [comment] 2020-04-23 22:28
> > so no libsimdjson.so/a?
> 
> Would you be interested in maintaining prebuilt binaries for various versions of major Linux distributions, freeBSD, macOS and Windows?
> 
> > I have to download cpp and h.
> 
> That's one way. Under Windows, you can use vpkg. Under Linux, you can pull the package as part of the system (e.g., apt-get install).
> 
> > Single header is only h/hpp.
> 
> `cat simdjson.h simdjson.cpp > onebigballofcode.h`
> 
> then
> 
> `#include "onebigballofcode.h"`

1. If that is true, why do we have ccp and h file. Why not one big hpp file?
2. Why not some static or dynamic library, like "normal people"? ;-)

**Comment by lemire** [comment] 2020-04-24 02:34
> Why not some static or dynamic library, like "normal people"? ;-)


Can you point to examples of what you mean?

**Comment by ostri** [comment] 2020-04-24 08:44
Below is the CMakeLists.txt file which is based on simdjson.{?pp} and helps me integrate simdjson
parser in my application.
As a user of simdjson I want to use its services, and (mainly) I am not interested in its implementation, as long as it delivers the services it advertises.

Interface between my application and simdjson is header file and api stored in library (i.e. compiled simdjson.cpp). If header file is huge and bloated it slows down my application recompilation, even if it is only referenced (i.e. include). You know, that there is a lot of application recompilation during the development.

I saw "simdjson" approach to the service delivery in the past in two cases:
1. EARLY: project is in early stage and the distribution infrastructure is not in place, so we deliver sources to the "customer" to get the feedback ASAP. We will bother with packaging later.
2. EMBEDDED: Service/tool is intended for embedded systems, we don't know the architecture it will be implemented on and we are leaving customer to "customize" our product for the target platform. We also allow the customer to finetune at compile time all essential constants that influence memory consumption.

Let me be frank. (ON)

I am fedora/redhat/debian/you name it user. I want to user your library. Give me simple header I can include in my application and library I can link with. Simple installation&setup (e.g. yum,dnf, you name it) and (human) documented API is also essential.
At this stage I do not care that you need to use inline to be fast. I do not care, that you have to  embed logic into header files, since templates are only in header files. I do not care that you are resource limited and you can not provide binary distribution for windows, linux, aix, macos, android, ...
But I care that I have a free json parsing library on my disposal that is extremely fast.

Let me be frank. (OFF)

I suggest to make a benchmark, if there is any significant speed handicap if the cpp file is compiled and stored in library, that is later linked to the main application. 
I believe there should be no significant runtime difference.
Later on we need to gradually move portions of the header file, which are not part of interface, but part of implementation into the cpp files. 
We can start with io part, which is slow by definition and inlines should not have any influence on it. 
The header file is going to contain only real library interface and those methods that needs to be implemented inline because of performance.
I am sure that modern compilers can minimise the amount of such code.

This is how I integrated simdjson in my application. And I am sure 95% of c++ developers would do the same.

```
set (lib_name  "simdjson")
add_library(${lib_name} STATIC "")
target_compile_options(${lib_name} PRIVATE ${compile_options})
target_sources(${lib_name} PRIVATE
  simdjson.cpp
  simdjson.h
)
```
