### ISSUE TITLE
Null terminated strings are considered invalid

### ISSUE THREAD

**Issue by Oipo** [simdjson/simdjson#1097] opened 2020-08-06 07:21 UTC
The following code:
```c++
        const char *str = "{\"id\":20,\"val\":\"five hundred\"}\0";
        auto d = parser.parse(str, strlen(str)+1); // this is an obvious weird thing to do, but it approximates what I do in my own code best.

        return (uint64_t)d["id"];
```

Results in this error:
```c++
terminate called after throwing an instance of 'simdjson::simdjson_error'
  what():  The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc.
```
As soon as the parser doesn't see a \0, everything is fine. Is this intended behaviour that I have to workaround?

**Comment by TkTech** [comment] 2020-08-06 07:55
The entire buffer isn't being parsed - this is an error, and is an invalid document. You could replace that `\0` with anything, like `t`. This is not a bug, but should be an error in any well-formed parser.

**Comment by TkTech** [comment] 2020-08-06 08:06
To be clear, your string is already null terminated implicitly. There is no reason to add another `\0`.

`const char *str = "{\"id\":20,\"val\":\"five hundred\"}\0";` gives you the string `{\"id\":20,\"val\":\"five hundred\"}\0\0` while `const char str[] = {'[', '1', '2', ']', '\0'}` would do what you seem to be trying to do.

**Comment by Oipo** [comment] 2020-08-06 09:04
Thanks for the clarification.

The reason I ask is because rapidjson explicitly checks for it in their [code](https://github.com/Tencent/rapidjson/blob/master/include/rapidjson/reader.h#L570). A cursory check seems to indicate that the following libraries do support null-terminated json documents explicitly: [nlohmann/json](https://github.com/nlohmann/json/blob/develop/single_include/nlohmann/json.hpp#L7457), [jsoncpp](https://github.com/open-source-parsers/jsoncpp/blob/master/src/lib_json/json_reader.cpp#L296)
And a few for which I think they just ignore anything after the closing bracket: [ultrajson](https://github.com/ultrajson/ultrajson/blob/master/lib/ultrajsondec.c#L633),  [json-parser](https://github.com/udp/json-parser/blob/master/json.c#L886)

It's just difficult that the [spec](https://tools.ietf.org/html/rfc7159) says nothing concrete about null terminated documents. Given these things, I am wondering what makes you say that including one - or more - null terminators makes it an invalid document?

**Comment by lemire** [comment] 2020-08-06 15:13
@Oipo 


First, let us define what a null terminated string is in C. The string `const char * c = "12345";` in C is null terminated. Its length is five. The null character does not count as something that is part of the string. The null character is metadata.

So if `const char * c = "12345";` is a null terminated string, its content is "12345". It is not "12345\0".

If some code considers that the string content is "12345\0", then this code is buggy.



>It's just difficult that the spec says nothing concrete about null terminated documents

Section 2 of the JSON specification provides the grammar. Exactly four characters are allowed before and after the elements, \n, \t, \r, ' '. Everything else is disallowed.

Yes, the specification does say whether null terminated strings are allowed. But section 2 in the specification is a grammar. If something is not included in a grammar, **then it is not allowed**. 

Note that a JSON input string cannot be represented as a null terminated string in general because a JSON input can contain null characters inside the strings. It is thus unsafe to use null terminated strings for JSON unless you somehow disallow null characters (which the spec does not allow you to do).

> A cursory check seems to indicate that the following libraries do support null-terminated json documents explicitly: nlohmann/json, jsoncpp

The vast majority of parsing libraries do not follow the standard, so that it is not a decisive argument. Many libraries tolerate 'garbage' after the JSON document has ended, including invalid unicode characters. But that behaviour is clearly outside of the specification.

You'd still have a great point if it was ubiquitous to tolerate null characters at the end. 



Let us see what happens if you load a document with a final nul in JavaScript:

<img width="453" alt="Screen Shot 2020-08-06 at 10 55 51 AM" src="https://user-images.githubusercontent.com/391987/89547516-db90e980-d7d3-11ea-8ece-958b2fa69400.png">

As you can see, it does not work.

What about Python?

<img width="648" alt="Screen Shot 2020-08-06 at 10 59 44 AM" src="https://user-images.githubusercontent.com/391987/89547602-f6fbf480-d7d3-11ea-821b-93200a66978e.png">


Nope.

So if you pad the end of your JSON strings with nulls, they won't parse in JavaScript and Python. The spec disallows such padding.


It seems to me that the conclusion is clear. Even if padding with null characters may be allowed by some librairies, such padding is not allowed in the specification and the resulting JSON documents won't be portable.


So I don't think it is a bug in simdjson.

Closing.

**Closed by lemire** 2020-08-06 15:13 UTC
Labels: bug

**Comment by lemire** [comment] 2020-08-06 15:26
@Oipo The following should work just fine, as remarked by @TkTech 👍 

```C++
        const char *str = "{\"id\":20,\"val\":\"five hundred\"}";
        auto d = parser.parse(str, strlen(str));
        return (uint64_t)d["id"]
```

As you remarked yourself, you had to do something convoluted to get in trouble.

**Comment by Oipo** [comment] 2020-08-06 18:16
I regret using the const char* as an example, as it detracted from my original point. I actually have to deal with a combination of legacy and new microservices, of which the legacy services send \0 over the network. I guess my minimal reproducible example was too minimal. Oh well.

Thanks for explaining the stance of simdjson, but although we could have a discussion on whether following the spec to a T is a smart move or not, I don't think that'll help either of us. I guess there just is a mismatch in my use-case and what simdjson provides, I'll advise the company I work for to use RapidJSON instead.

**Comment by lemire** [comment] 2020-08-06 18:29
> which the legacy services send \0 over the network

If the '\0' is at the end of the strings, why don't you trim it off before sending the content to the parser? As I think that I have convincingly argue, that '\0' should not be considered to be part of the JSON document. It is literally one line of code to remove a zero padder.

> I'll advise the company I work for to use RapidJSON instead.

RapidJSON is an excellent choice.  It also tolerates some level of garbage at the end of the input. It is the only way I know of that it differs from the standard.

**Comment by Oipo** [comment] 2020-08-06 18:36
> > which the legacy services send \0 over the network
> 
> If the '\0' is at the end of the strings, why don't you trim it off before sending the content to the parser? As I think that I have convincingly argue, that '\0' should not be considered to be part of the JSON document. It is literally one line of code to remove a zero padder.

Because some of the incoming data does have the \0 and some does not. I could introduce if statements or strlen() but that's still more effort than using RapidJSON.

**Comment by jkeiser** [comment] 2020-08-06 19:24
> Because some of the incoming data does have the \0 and some does not. I could introduce if statements or strlen() but that's still more effort than using RapidJSON.

I'm curious, what are you sending as the length to simdjson? If you already have the length and there's a single optional \0 at the very end, a simple `parser.parse(buf, buf[len] ? len : len - 1)` ought to do the job. Or a wrapper function you call everywhere to parse:

```c++
int parse_json(dom::parser &parser, const char *buf, size_t len) { return parser.parse(buf, buf[len] ? len : len - 1); }
```

Hate for you to have to run a slower parser over this--I was kinda of hoping to get more people to use it and then claim I made a dent in global warming :)--but I understand everybody's value judgements are different :)
