### ISSUE TITLE
moving parser instances invalidates elements, use std::unique_ptr<dom::parser> instead

### ISSUE THREAD

**Issue by cculianu** [simdjson/simdjson#1246] opened 2020-10-24 10:21 UTC
**Describe the bug**

- It appears the `simdjson::dom::parser` and `simdjson::dom::element` don't like to be moved around or put into certain `std` containers.  They crash if put into any container but a `std::list`.  Likely they don't like to be copied/moved. I get a `SIGSEGV` when putting them into a `std::vector`, for example.

- ~~It also appears that if I keep `simdjson::dom:element` around for longer than the `parser` that last manipulated it, serializing via `simdjson::to_string` also fails later with a `SIGSEGV`.~~ (Update: Ok, so this is an API limitation -- fair enough -- but then one should allow `dom::parser`s to be copied and put into vectors if they must be married to their `dom::element`!!).

**To Reproduce**

See this sample project that illustrates the problem(s):

https://github.com/cculianu/simdjson-bugs

In particular this code here: https://github.com/cculianu/simdjson-bugs/blob/09e0d3ded2bf51296a9c29d583ba7ba1aac4ae04/main.cpp#L59

```c++
    std::vector<std::tuple<std::string, simdjson::dom::parser, simdjson::dom::element>> results;
    for (const auto & f : files) {
        std::string buf = slurpFile(f); // reads file, returns entire file contents as a string
        std::cout << "Read \"" << f << "\" - size: " << buf.size() << "\n";
        simdjson::dom::parser parser;
        simdjson::dom::element parsed;
        auto error = parser.parse(buf).get(parsed);
        if (error) throw std::runtime_error(std::string{"Failed to parse "} + std::string{f});
        results.emplace_back(std::string{f}, std::move(parser), std::move(parsed));
    }
    for (const auto & [name, parser, parsed] : results) {
        std::cout << "File: \"" << name << "\"; serializing...\n";
/// ---- CRASH ON BELOW LINE ----
        std::cout << "First 100 bytes, reserialized: " << simdjson::to_string(parsed).substr(0, 100) << " ...\n";
        std::cout << std::string(80, '-') << "\n";
    }
}
```

The crash is in the second loop -- the one that calls `to_string`.  The crash happens when it minifies the dom to a string. However, if we use `std::list` instead of `std::vector` for the container above (which involves no moving-around of elements on `emplace_back`), it works perfectly.

~~Here is another case where it crashes:~~ UPDATE: It appears the below is expected behavior. :(  

```c++
    std::list<std::pair<std::string, simdjson::dom::element>> results;
    for (const auto & f : files) {
        std::string buf = slurpFile(f); // reads file, returns entire file contents as a string
        std::cout << "Read \"" << f << "\" - size: " << buf.size() << "\n";
        results.emplace_back();
        auto & [name, parsed] = results.back();
        name = f; // assign
        simdjson::dom::parser parser; // <--  it appears simdjson doesn't like this object to die before the element?!
        auto error = parser.parse(buf).get(parsed);
        if (error) throw std::runtime_error(std::string{"Failed to parse "} + std::string{f});
    }
    // at this point the parser used for each result is dead.
    for (const auto & [name, parsed] : results) {
        std::cout << "File: \"" << name << "\"; serializing...\n";
/// ---- CRASH ON BELOW LINE ----
        std::cout << "First 100 bytes, reserialized: " << simdjson::to_string(parsed).substr(0, 100) << " ...\n";
        std::cout << std::string(80, '-') << "\n";
    }
```

**Configuration (please complete the following information if relevant):**
 - OS: Debian 10 and also macOS Mojave 
 - Compiler Apple clang version 11.0.0 and gcc 8.3.0
 - Version 0.6.0
 - Processor Intel Core i9
 - Using the **single file header** implementation (I didn't even try the compiled non-single-file header) 

### Suggestion

- If these operations are not permitted (such as moving or copying) -- then you should likely make the unsafe operations forbidden by the C++ type system.
- If there are lifecycle constraints e.g. the `parser` must outlive `element` -- then this needs to be enforced by the object model.

**Comment by cculianu** [comment] 2020-10-24 10:47
I was also able to produce the crash if the `simdjson::dom::parser` is destructed by the `simdjson::dom::element` outlives it.  It appears the API really requires the parser to outlive the elements?!  If so -- then this needs to be enforced by the C++ type system....

**Comment by jkeiser** [comment] 2020-10-24 16:56
C++ is unfortunately not rust. I don't think there's any way to enforce lifetimes like this at compile time. Traditionally, as far as I know, invariants in the documentation are the best we have. And we know people don't really read that (not a judgement, just a statement of fact).

We *could* make a runtime check with reference counting, but unless the optimizer is very clever it'd add runtime cost. And it's still not compile time type enforcement like you and I would both want. 

If someone has a clever solution I'm all ears, but I'm leaning towards "by design, because c++ makes me sad" :)

**Comment by lemire** [comment] 2020-10-24 16:57
Thanks for the report...

The documentation states:

> The parsed document resulting from the parser.load and parser.parse calls depends on the parser instance. Thus the parser instance must remain in scope.

So unless I misread the code, there is no bug. It works as intended, as per our documentation. I believe it is also documented in the API.

Maybe our document is not as clear as it could be. We should discuss how it can be improved.

Regarding the proposal...

"If these operations are not permitted (such as moving or copying) -- then you should likely make the unsafe operations forbidden by the C++ type system. If there are lifecycle constraints e.g. the parser must outlive element -- then this needs to be enforced by the object model."

The data is owned by the parser, this is by design. It is akin to the following C++17 code:

```C++
#include <string_view>
#include <string>


std::string_view get_strv(std::string& s) {
    return std::string_view(s.data(), s.size());
}
```

(In fact, because we make extensive use of `std::string_view`, it is a close analogy.)

This sample is perfectly fine C++ code. There is a contract in there, however. The `std::string_view` is only valid as long as the `std::string` remains in scope. You can put the `std::string_view` instance in a container or wherever, but if the `std::string` goes out of scope, you will have problems.

Or you may consider this example...

```C++
#include <vector>

std::vector<int>::iterator get(std::vector<int> & x) {
    return x.begin();
}
```


Again, this is perfectly fine C++. You can take these iterators and store them in containers or do whatever else with them. They will work just fine. Don't let the `std:vector` go out of scope, however.




Here our contract is the same way, the ownership of the data is in the parser instance. If it goes out of scope, everything that pointed to it is invalid. It works like STL containers or std::string_view.

If you have concret proposals, I think we will consider them seriously... But please consider the above.

**Comment by jkeiser** [comment] 2020-10-24 16:58
Oh, and yes, the DOM values refer to memory owned by the parser, which is overwritten on each parse () call. The goal being to avoid reallocation in the typical "parse and use the document, throw it away" loop.

**Comment by cculianu** [comment] 2020-10-24 17:14
@lemire Ok fair enough -- So the `dom::element` object is akin to a `std::string_view` -- and it really points to its `dom::parser`'s data? *sigh*.  Why call it a parser then??  That's.. unintuitive...

And.. even so.. you would think moving it would work.  But I guess some implementation detail means moving is not a simple pointer swap, is it?

I would consider hiding all this stuff behind heap-allocated memory (so that you can move the damned parsers!) and using something that is semantically equivalent to the "copy-on-write" pattern -- this way you can pass these objects around and a shared reference count is maintained.  Only when you write to one of the shared references does it "detach" and make a private copy.  This would fix a lot of the surprises and gotchas here, I think, and make the library far more useful.  You may find it won't be much of a performance hit to do this -- at least not for parsing or serializing -- which is what you focus on.  It would just make the library more useful.

Just some food for thought.  Thanks for the response.

Given the library's surprising API I am not sure I feel comfortable switching to it -- since my project doesn't really need the speed.  But your library is *incredibly* fast -- like 20x or more what I currently use.  Pretty in-freakin'-credible.  Just.. man.. work on the ergonomics of it.... and you will pwn!

Thanks,

-Calin

**Comment by lemire** [comment] 2020-10-24 17:14
Tools are incredibly important.


The following is seemingly correct C++. It even runs and appears to work... but it is obviously unsafe (it will "appear to work" until it does not). 

```
#include <iostream>
#include <vector>

std::vector<int>::iterator get(std::vector<int>& x) {
    return x.begin();
}

std::vector<int>::iterator  pointer_to_1() {
  std::vector<int> vec;
  vec.push_back(1);
  return get(vec);
}

int main() {
  std::cout << *pointer_to_1() << std::endl;
}

```

I tried different compilers, including Visual Studio, clang... and none of them issue any warning whatsoever.

But any memory sanitizer, or tools like valgrind will immediately spot the error.

And that's the key. It is not really possible to make these mistakes easily if you run your code through tools. I argue that modern C++ is supposed to work in tandem with sanitizers and tools like valgrind.

**Comment by cculianu** [comment] 2020-10-24 17:20
> The following is seemingly correct C++. It even runs and appears to work... but it is obviously unsafe (it will "appear to work" until it does not).

Fair enough.  Plenty of legal gotchas in C++.  

But it's possible to write libraries without this surprising behavior.  vector is a very low-level type close to the metal.  It provides little in the way of niceties.. It's old and lean and mean.

I realize your library is the fastest thing on the planet, so it has a lot of leeway here.

But by the same token, a big huge parsed JSON document can live behind a heap-allocated memory area with a shared pointer wrapping it and copy-on-write semantics or other niceties...  -- we can have nice things in 2020!

**Comment by cculianu** [comment] 2020-10-24 17:24
Also: how do I pre-parse a JSON document and safely store the parse results somewhere for later processing?  It seems there is no easy way to do that.  The parser is storing the state of the document but with no way to access it without calling parse() again!  There is no object to "hold" my document...?

**Comment by cculianu** [comment] 2020-10-24 17:38
I'm closing this since it's not a bug -- just a low-level library for masochists.  Thanks for the reply.

**Comment by lemire** [comment] 2020-10-24 17:42
@cculianu Thanks for the feedback and the good words.

I think that I can speak with some confidence that both @jkeiser  and myself do understand and empathize with your comments. We do not disagree with your sentiment.

There might be ways to do as you suggest... but I am sure that you appreciate that it can harder than it seems. After all, if it were easy, people would have written a competitor to STL by now. If you can get the same performance and greater safety... Well... one could become quite famous. Note that I am not saying that writing a better STL is not possible. I am just saying that it might be hard. If you want to have pointers that track what happened to the container... all of it without tanking the performance... I have yet to see any such proposal...


> Also: how do I pre-parse a JSON document and safely store the parse results somewhere for later processing? It seems there is no easy way to do that. The parser is storing the state of the document but with no way to access it without calling parse() again! There is no object to "hold" my document...?

You have to keep the parser around.

> Why call it a parser then?? That's.. unintuitive...

Yes. I agree. Just changing the name could help a great deal make the result more intuitive.

> Thanks for the reply.

Thanks for the report.

**Comment by jkeiser** [comment] 2020-10-24 18:58
One thing I'll say: we don't just care about parsing performance, we also care about *usage* performance. This is why we released the new on demand api with 0.6.

This issue should be a lot better with our new on demand api:: at the least, it should tell you at runtime if you try to employ this kind of pattern :)

**Comment by jkeiser** [comment] 2020-10-24 19:00
We have considered a way to detach and keep a document around, and it's certainly possible ; up until now, no one has really asked for it. That's certainly a reasonable ask and wouldn't be hard to implement. Would that solve problem you want to solve?

**Comment by jkeiser** [comment] 2020-10-24 19:06
I think we should leave this open a bit longer to discuss ; many possible changes have been hinted at here and I'd hate to lose them without opening relevant issues.

**Comment by jkeiser** [comment] 2020-10-24 19:25
The suggestions I saw, which are not mutually exclusive:

* Rename parser to make it clear that there is also a document storage there. I'm unclear what intuitive name would make this clear, but I'm open to it :)
* Rename element to something like string_view (perhaps element_view?), so people don't assume it actually stores anything.
* Allow documents (or perhaps even elements) to be detached from the parser, and make a new one for the next parse
  - Recall the original DOM parser implementation allowed for this; we removed it for time, and decided to wait and see if it ever got asked for :)
* Use reference counting to prevent the original document from being invalidated the parser going out of scope, or a second parse() call, from invalidating the original document
  - Could even automatically detach and make a new document when this happens
  - There are potential concerns with this: it is not obvious that when keep a single `element` around, the entire document will stay in memory!

**Comment by jkeiser** [comment] 2020-10-24 19:27
@lemire wait, why is this crashing again? The parser *isn't* going out of scope, he's keeping it around and using `std::move` to put it in the vector, which ought to work ...

**Comment by jkeiser** [comment] 2020-10-24 19:35
I think we've been talking about the wrong issue. As much as I'd still like to solve the "it sucks that you can't keep an element around without also keeping the parser," this seems to be "when I move the parser onto a vector, something seems to get unexpectedly invalidated and we crash." The code sample that doesn't keep `element` around is expected behavior and falls under the first category. The code sample in the description now is something I think should work.

@cculianu I see two code snippets in the original issue description, and you may have edited, so to be terribly pedantic: is this code the code that crashes? I expect it to work, though I've been wrong before :)

```c++
   std::vector<std::tuple<std::string, simdjson::dom::parser, simdjson::dom::element>> results;
    for (const auto & f : files) {
        std::string buf = slurpFile(f); // reads file, returns entire file contents as a string
        std::cout << "Read \"" << f << "\" - size: " << buf.size() << "\n";
        simdjson::dom::parser parser;
        simdjson::dom::element parsed;
        auto error = parser.parse(buf).get(parsed);
        if (error) throw std::runtime_error(std::string{"Failed to parse "} + std::string{f});
        results.emplace_back(std::string{f}, std::move(parser), std::move(parsed));
    }
    for (const auto & [name, parser, parsed] : results) {
        std::cout << "File: \"" << name << "\"; serializing...\n";
/// ---- CRASH ON BELOW LINE ----
        std::cout << "First 100 bytes, reserialized: " << simdjson::to_string(parsed).substr(0, 100) << " ...\n";
        std::cout << std::string(80, '-') << "\n";
    }
}
```

**Comment by jkeiser** [comment] 2020-10-24 19:36
(The parser is a move-only object, and is supposed to support move. That's actually why it uses unique_ptr internally for allocated memory.)

**Comment by cculianu** [comment] 2020-10-24 23:10
> @cculianu I see two code snippets in the original issue description, and you may have edited, so to be terribly pedantic: is this code the code that crashes? I expect it to work, though I've been wrong before :)

@jkeiser Yes, that code sample does crash.  You can check-out and compile the sample project (which has simdjson as a submodule) here: https://github.com/cculianu/simdjson-bugs

It's in the function in `main.cpp` called "void crashy()`

**Comment by lemire** [comment] 2020-10-25 16:22
@cculianu @jkeiser I have renamed the issue and marked it as a potential bug.

You should be able to move the parser and the elements.

**Comment by lemire** [comment] 2020-10-25 17:33
Ah. So I totally misunderstood the bug report?

Here @cculianu wants to "store" documents. We could easily make this possible. The parser owns the document. The document instance can be moved. That's what @cculianu is really trying to do, awkwardly through no fault of his own. It does seem that our API is constraining him in a poor way. Maybe this should be a separate issue.

Going back to the moves... Pointers or iterators into something that move are generally unsafe in C++. [If you move an STL container, then the iterators to the container become unsafe](https://stackoverflow.com/questions/11021764/does-moving-a-vector-invalidate-iterators?rq=1).  It may work most of the time but then it may crash later.

A good solution is to just avoid moving `parser` instances. For example, you can use `unique_ptr` for this purpose:

```C++
  typedef std::tuple<std::string, std::unique_ptr<parser>,element> simdjson_tuple;
  std::vector<simdjson_tuple> results;
  for (const auto &f : files) {
    std::unique_ptr<dom::parser> parser(new dom::parser{});
    element root;
    auto error = parser->load(f).get(root);
    if (error) {
      throw std::runtime_error(std::string{"Failed to parse "} +
                               std::string{f});
    }
    results.emplace_back(f, std::move(parser), root);
  }
  for (auto &t : results) {
    std::cout << "File: \"" << std::get<0>(t) << "\"; serializing...\n";
    std::cout << "reserialized: " << simdjson::to_string(std::get<2>(t)) << " ...\n";
  }
```



What about our use case? Could we allow the moves. Ok. Let us reason this out. An element owns `const dom::document *doc`. The `document doc{}` lives inside the `parser` (which owns it). The `document` owns two things... `std::unique_ptr<uint64_t[]> tape{};` and `std::unique_ptr<uint8_t[]> string_buf{};`. I think that what makes moving the parser unsafe with respect to the elements is the pointer to the document. I am not C++ grammar expert, but if you move an instance, I don't think it follows that the old address remains valid or that the moved instance will remain at the same address. So I expect the `const dom::document *doc` owned by the element to be unsafe following a move. It may still work or it may crash badly.

@jkeiser Unless you have a better idea, the way I would fix this issue is by indicating that elements following a move of the `parser` instance are unsafe, and to recommend `std::unique_ptr` wrapping.

I'll open an issue meanwhile regarding how we should discuss allowing users to retrieve the document instance from the parser. 


```C++
  std::vector<dom::document> results;
  dom::parser parser(new dom::parser{});
  for (const auto &f : files) {
    element root;
    auto error = parser->load(f).get(root);
    if (error) {
      throw std::runtime_error(std::string{"Failed to parse "} +
                               std::string{f});
    }
    results.emplace_back(parser.get_document_copy());
  }
  for (auto &t : results) {
    std::cout << "reserialized: " << simdjson::to_string(t.root()) << " ...\n";
  }
```

But this requires more discussion.

**Comment by lemire** [comment] 2020-10-25 17:38
The related issue is https://github.com/simdjson/simdjson/issues/679

**Comment by jkeiser** [comment] 2020-10-25 17:59
Good catch, you're absolutely right, that's the issue. Elements become invalid as soon as the document is moved.

**Comment by lemire** [comment] 2020-10-25 18:07
@cculianu I am hopeful that if you just replace your "dom::parser" instances by "std::unique_ptr<dom::parser>" then it will work out well.

Thanks again for the report!

**Comment by jkeiser** [comment] 2020-10-25 18:15
We should als investigate the cost of using shared_ptr internally to prevent this sort of issue entirely. It could be modem c++ compilers optimize it; it is certainly likely they have focused some effort on it.

**Comment by jkeiser** [comment] 2020-10-25 18:17
I say this because on my on demand work I realized that most reference counts are entirely knowable (and largely elidable) at compile time.

**Comment by lemire** [comment] 2020-10-25 18:34
The easy fix is to avoid the indirection. Instead of going through the document and then to the tape, point directly at the tape. Under a move, the tape remains where it is. Of course, you still need to worry about the string buffer so there might be two pointers.

**Comment by lemire** [comment] 2020-10-25 18:35
It is like this... we have the parser that owns the document that ows two pointers. The two points are fixed in stone. Both the parser and the document move. Our elements point at the document. The document moves... and the element has now no way to know where it has gone, and it has lost track of the tape.

**Comment by jkeiser** [comment] 2020-10-25 18:48
Yeah, it would fix this issue. A shared_ptr would let you keep an element around without explicitly saving the document, though, and I suspect would also let you check for outstanding instances when parse() is called again, and avoid reusing the document.

**Comment by cculianu** [comment] 2020-10-25 20:47
Hey guys thanks so much for the thoughtful attention.  I am ok with just using a `unique_ptr`. Originally I didn't understand how your lib is architected.

After playing with it for a few days I must say it's *incredibly* fast.  Especially on very large documents. It absolutely screams and blows everything out of the water.  I inspected how it's written -- it used very modern C++ and is oriented towards speed. You even have your own double parser!  Very impressive!

I feel a little bad for having "complained" to you guys about the API and other things.  I think it's perfectly ok to use `unique_ptr` to store parsers.  In fact, that's not a bad idea.  You don't have to modify your API on my account.

I ended up using your library as a parsing backend -- and then used it to transfer data into my own generic containers. I am doing this "on the fly" now and even with all the overhead of copying the data out into my maps, lists, etc containers -- it still is 2x faster on small documents and 5x-10x faster on large documents!!

I am very happy with my setup now -- and don't feel constrained by your API at all.  You guys focused on speed and this is basically a parser, a very very fast parser.  It's up to the application programmer what to do with the parsed data after that point.

I think your library is fine and great.  Please accept my apology for having complained to you guys earlier.  I.. just didn't get it.  Having read your code over and over again to learn the API and internals I am very impressed with just how high quality the code is.

Please accept my apology again. And thank you very much for this most excellent library!!

**Comment by lemire** [comment] 2020-10-25 20:53
@cculianu I misread your issue (it seems @jkeiser did too).

I should have asked more questions. Sorry.

**Comment by cculianu** [comment] 2020-10-25 20:55
It's ok -- I think my issue anyway is bizarre.  Like you said -- moving strings or vectors doesn't guarantee stable iterators (short string optimization is a thing so a move is not always a pointer swap and is not possible).

Please don't worry about it -- if the parser moves its "references" are invalidated.  That's a fine constraint.  I should have read your API comments better.  I think this is really a non-issue tbh.  

However it would be nice to be able to store parsers and then ask them for data later -- right now that doesn't seem possible.

But parsing is *so bloody fast* anyway -- it seems ok to me to just store the JSON itself somewhere and parse it on-the-fly.  I'm perfectly ok with how your library is written.  You don't need to change anything -- keep it fast is all you need to do and have done !!

**Comment by jkeiser** [comment] 2020-10-25 22:03
We really do want to remove the "sharp edges" from the Api as well. People shouldn't have to choose between fast and easy. Otherwise most people reach for easy, servers are slow and suddenly the polar ice caps are melting. 

So your experience is instructive, even if you have moved past it. Thanks!

**Closed** 2020-10-26 12:40 UTC
Labels: bug (unverified), discussion, documentation

**Comment by lemire** [comment] 2020-10-27 00:30
> I think we should leave this open a bit longer to discuss ; many possible changes have been hinted at here and I'd hate to lose them without opening relevant issues.

I would recommend creating new issues that are more focused.
