### ISSUE TITLE
External SIMD library?

### ISSUE THREAD

**Issue by lyssdod** [simdjson/simdjson#1716] opened 2021-09-17 12:27 UTC
Hi,

Have you considered using something like https://github.com/p12tic/libsimdpp to generalize SIMD functions? This would allow 32-bit support as well

**Comment by lemire** [comment] 2021-09-17 12:48
This is a duplicate of https://github.com/simdjson/simdjson/issues/1091

**Closed by lemire** 2021-09-17 12:48 UTC
