### ISSUE TITLE
Assert failure when compiling in debug mode (with assertions) on invalid JSON during object lookup after get_bool failure (On Demand)

### ISSUE THREAD

**Issue by strager** [simdjson/simdjson#1660] opened 2021-07-18 04:05 UTC
**Describe the bug**
I'm parsing the following invalid JSON:
```json
{"globals":{"a":{"shadowable":[}}}})
```

If I call `get_bool()` on `shadowable`'s value, then looking up another property in the `a` object crashes with an assertion failure inside simdjson.

**To Reproduce**
https://gist.github.com/strager/81e48e5719f0ad39b49220faa1881e46

Output:
```
[snip]
> Running strager_bug ...
ondemand_misc_tests: ../include/simdjson/generic/ondemand/value_iterator-inl.h:292: simdjson_result<bool> simdjson::fallback::ondemand::value_iterator::find_field_unordered_raw(const std::string_view): Assertion `has_value' failed.
```

**simjson release:** v0.9.6 and master (774999ee95a8fbca36c7d914ae47c676b58f7938)

**Configuration:**
 - OS: Linux Mint 20 Ulyana (based on 20.04 Focal)
 - Compiler: clang version 11.0.0 (176249bd6732a8044d457092ed932768724a6f06) x86_64-unknown-linux-gnu

**Indicate whether you are willing or able to provide a bug fix as a pull request**
Willing: Yes. Planning: No.

----

**Describe the bug**
 I'm parsing the following invalid JSON:
```json
{"":],"hello":[[]}}
```

I look up `hello` and cast it to an `object`. After, I look up `world`. This second lookup crashes.

**To Reproduce**
https://gist.github.com/011728dca24a3ab03a9e34eaac2371e3

**Comment by strager** [comment] 2021-07-18 04:07
This might be related to #1632. We're getting INCORRECT_TYPE (supposedly recoverable), but perhaps we should get TAPE_ERROR (unrecoverable).

**Comment by lemire** [comment] 2021-07-18 17:07
You say it 'crashes' when you seek to access a missing key as part of a broken JSON document.

I have written your test as follows:

```
  bool issue1660() {
    TEST_START();
    ondemand::parser parser;
    padded_string docdata =  R"({"globals":{"a":{"shadowable":[}}}})"_padded;
    ondemand::document doc;
    ASSERT_SUCCESS(parser.iterate(docdata).get(doc));
    ondemand::object globals;
    ASSERT_SUCCESS(doc["globals"].get(globals));
    for (auto global_field : globals) {
      ondemand::value global;
      ASSERT_SUCCESS(global_field.value().get(global));
      ondemand::json_type global_type;
      ASSERT_SUCCESS(global.type().get(global_type));
      ASSERT_EQUAL(global_type, ondemand::json_type::object);
      ondemand::object global_object;
      ASSERT_SUCCESS(global.get(global_object));
      ondemand::value shadowable;
      ASSERT_SUCCESS(global_object["shadowable"].get(shadowable));
      ASSERT_ERROR(shadowable.get_bool(), INCORRECT_TYPE);
      ondemand::value badvalue;
      auto error = global_object["writable"].get(badvalue);
      if(error == SUCCESS) {
        return false;
      } else {
        break;
      }
    }
    TEST_SUCCEED();

```


It does what I expect. What seems to be a problem is the debug mode where there might be an assert. I have not verified that. Let me do so.

**Comment by lemire** [comment] 2021-07-18 17:10
Ah. Yes. Yes. Verified. We have an assert which cause trouble in debug mode.

Why is that there?

**Comment by lemire** [comment] 2021-07-18 19:46
Ok. There is an interesting puzzle.

**Comment by lemire** [comment] 2021-07-18 20:46
It is a duplicate of https://github.com/simdjson/simdjson/issues/1632

I will merge the issues.

**Closed by lemire** 2021-07-18 20:46 UTC
Labels: bug (unverified)

**Comment by lemire** [comment] 2021-07-18 21:17
> This might be related to #1632. We're getting INCORRECT_TYPE (supposedly recoverable), but perhaps we should get TAPE_ERROR (unrecoverable).

I think that's the same issue, yes. If you read what @jkeiser wrote in his own bug report, he says he is working on doing document validation when return an INCORRECT_TYPE. Currently, we return INCORRECT_TYPE while assuming that the document is valid, so that it is recoverable. In your cases, it is not recoverable, so we should just die there... but we can't tell right now.

Your test case is still super useful because it will allow us to verify the work.
