### ISSUE TITLE
Implement an ability to parse integers that exceed 64 bits

### ISSUE THREAD

**Issue by saleyn** [simdjson/simdjson#2108] opened 2024-01-08 15:20 UTC
Presently the parse fails to parse valid JSON input containing numbers larger than `1 << 64`.

The question is how to represent such input, and whether to include support for big numbers.  A possible option would be to just introduce a type that would be a derivative of `std::string_view` for representing such integers, and leaving up to the library's user to deal with parsing.  Or maybe to be able to set up a lambda called for large numbers, so that a user can handle the actual parsing of the bignum.

**Comment by furkanusta** [comment] 2024-01-08 17:11
These two links might be useful
https://github.com/simdjson/simdjson/discussions/2015
https://github.com/simdjson/simdjson/blob/master/doc/basics.md#general-direct-access-to-the-raw-json-string

**Comment by saleyn** [comment] 2024-01-08 19:11
Is it possible to achieve the same when using not on-demand parser?
I.e.
```C++
  try {
    dom::parser parser;
    dom::element elm = parser.parse(str, size);
    return make_term(env, elm, opts);
  } catch (simdjson_error const& error) {
     ...
  }
```
Currently the parse function throws NUMBER_ERROR exception when I pass JSON `"2341341341234134112341343"`.

**Comment by lemire** [comment] 2024-01-08 19:51
Closing. This is a duplicate of https://github.com/simdjson/simdjson/issues/167

See also https://github.com/facebookincubator/velox/issues/8066#issuecomment-1858121217 (@Yuhta)


If you'd like to help @Yuhta with their PR, please reach out.

**Closed by lemire** 2024-01-08 19:51 UTC

**Comment by lemire** [comment] 2024-01-08 20:17
> Currently the parse function throws NUMBER_ERROR exception when I pass JSON "2341341341234134112341343".

It does so because this integer value cannot be represented in C++. The maximum integer type provided by C++ is `uint64_t`. So you either have to map it to a non-standard integer type, or to cast it to a floating-point in a lossy manner (you will not recover 2341341341234134112341343). If you have 2341341341234134112341343 in your JSON file, then it is unlikely that you started out with a floating-point number. You probably had some custom integer type. The DOM API is designed for exact parsing.

> A possible option would be to just introduce a type that would be a derivative of std::string_view for representing such integers, and leaving up to the library's user to deal with parsing. 

As @furkanusta  pointed out, the On Demand API is designed to give you full flexibility to parse as you see fit. It provides this exact functionality and much more.

**Comment by saleyn** [comment] 2024-01-08 20:28
I maintain a [simdjsone](https://github.com/saleyn/simdjsone/) project, which provides the binding for `simdjson`, and Erlang has built-in support for bignum integers.  The simdjson library is used to parse a JSON string into an Erlang term.  The issue is that some tests that use large integer values are not passing.  I look forward to @Yuhta's PR.

**Comment by lemire** [comment] 2024-01-10 15:20
In any case, please see https://github.com/simdjson/simdjson/issues/167

**Comment by saleyn** [comment] 2024-01-12 14:05
@lemire, yes, #167 is a very similar request.  I think either having an option of returning _all_ integers as strings or having a special  element type for bigint's and returning them as strings works.  In the first case the users can use a different string-to-integer parser.  In [simdjsone](https://github.com/saleyn/simdjsone) I use [this one](https://github.com/saleyn/simdjsone/blob/main/c_src/simdjson_lltoa.hpp), which is more performant than the one included in simjsone.

**Comment by lemire** [comment] 2024-01-12 14:58
The DOM parser does not keep a reference to the input. It is meant to be one pass: you consume the data and construct a DOM tree. The DOM tree does not point in the original document.

If that’s what you need then you must use the On Demand which is designed from the ground up for this purpose. If you want to provide your own number parser, we even document how to do it.

**Comment by saleyn** [comment] 2024-01-13 04:25
But if we have:
```c++
dom::parser parser;
dom::element elm = parser.parse(str, size);
return make_term(env, elm, opts);
```
then upon return of the `parser.parse()` call if the `elm` has some `string_view` components that have pointers to parts of the `str`, they would still be valid until `str` is destroyed, and the next call to `make_term` would be able to encode the `elm` DOM into the language-specific term value. No?

**Comment by lemire** [comment] 2024-01-13 18:50
> If my task is to create a hierarchical parsed tree of the whole JSON input, and then convert that tree to a language-specific representation, is the On-Demant parser suitable for that task?

Yes. It is. What you are doing, probably, is to take the JSON, convert it to a simdjson DOM and then you rewalk this simdjson DOM to convert it back to your own data structure. The idea with On Demand is that you can go straight from the json document to your data structure, bypassing the DOM tree construction.

The On Demand API requires a bit more care. For example, you should not revisit values more than once. You need to stream through the input from start to end.

From our main documentation...

<img width="1051" alt="Capture d’écran, le 2024-01-13 à 13 46 31" src="https://github.com/simdjson/simdjson/assets/391987/2703187a-e67e-4968-af5c-4f1a641c0bc9">



See the `simdjson2msgpack` benchmark:

https://github.com/simdjson/simdjson/blob/master/benchmark/json2msgpack/simdjson_ondemand.h

**Comment by saleyn** [comment] 2024-01-18 04:24
Thank you for the tip! I'll try the suggested on-demand approach.
