### ISSUE TITLE
simdjson doesn't build with latest VS2019 (c++17)

### ISSUE THREAD

**Issue by pps83** [simdjson/simdjson#736] opened 2020-04-19 18:14 UTC
I get tons of warnings and this error:

> src\simdjson.cpp(4829,14): error C4996: 'simdjson::dom::parser::Iterator': Use the new DOM navigation API instead (see doc/usage.md)

I use https://github.com/simdjson/simdjson/blob/master/singleheader/simdjson.h + .cpp

**Comment by jkeiser** [comment] 2020-04-19 18:42
This should be fixed in master, but singleheader wasn't up to date :) I went and updated it.

Can you re-pull master and use the headers from [the singleheader directory](https://github.com/simdjson/simdjson/tree/master/singleheader)?) and try again? Thanks.

**Comment by pps83** [comment] 2020-04-19 19:07
Even with the latest update it does not compile. [I created a PR](https://github.com/simdjson/simdjson/pull/738) to address two issues that break compilation with latest VS2019 (one of them is clearly a compiler bug, I filed a ticket with MSFT).

**Comment by jkeiser** [comment] 2020-04-19 19:38
Can you post your repro steps? I can't make this happen on master. Here's what I did:

```cmd
git checkout master
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_GENERATOR_PLATFORM=x64 ..
cmake --build .
```

If I do `start simdjson.sln` and build from there, it doesn't give me warnings either.

According to "Check for updates," I have the latest Visual Studio (16.5.4):

![image](https://user-images.githubusercontent.com/654882/79697955-7b813200-823a-11ea-8478-aaf100b92d66.png)

**Comment by pps83** [comment] 2020-04-19 19:58
I don't use cmake, I simply added simdjson.h / simdjson.cpp to my project. Did you enable c++17 in project settings (not sure c++17 is on by default)?

**Comment by pps83** [comment] 2020-04-19 20:09
The reason it builds and doesn't complain about warnings to you is because cmake disables these warnings: `4005;4996;4267;4244;4113`
In my project I don't do that, and I get tons of warnings from sindjson including those errors that I had do fix to make it compile.

**Comment by pps83** [comment] 2020-04-19 20:35
I just looked into fixing fopen for those who do not diable that secure BS from ms compiler, and I'm quite surprised that simdjson inlines `parser::read_file`. That's nonsense

**Comment by pps83** [comment] 2020-04-19 21:11
One other point. Amalgamation isn't done properly imo. It totally forces simdjson.h + dmalloc.h, while it must preserve original simdjson.cpp and simply "include" other headers and source files to ensure that amalgamated version is identical to non-amalgamated.

**Comment by lemire** [comment] 2020-04-20 15:02
@jkeiser  Please see issue https://github.com/simdjson/simdjson/issues/750 

We need to document usage for Visual Studio.

**Comment by lemire** [comment] 2020-04-20 15:17
@pps83 Can you explain how we are able to build... see the CI trace...

https://ci.appveyor.com/project/lemire/simdjson-jmmti/branch/master/job/l627w8qcx074hxor

I understand that our CMake may be silencing warnings, but you refer to errors.

Are you sure that you are not confusing warnings with errors?

**Comment by lemire** [comment] 2020-04-20 15:19
Here are some of our compilation flags...
`/std:c++17 /wd4005 /wd4996 /wd4267 /wd4244 /wd4113`

Removing some of these "wd" flags might trigger new warnings, but it should not cause "simdjson doesn't build with latest VS2019". Maybe you mean "simdjson generates warnings when building with VS2019"?

**Comment by lemire** [comment] 2020-04-20 15:26
I see now that it triggers what appears to be build errors. How strange.

**Comment by lemire** [comment] 2020-04-20 15:28
Ok. That's not how it is supposed to work. These are warnings, not errors...

> If the compiler encounters the use of a deprecated identifier or the standard [[deprecated]] attribute, a C4996 warning is thrown.

https://docs.microsoft.com/en-us/cpp/cpp/deprecated-cpp?view=vs-2019

**Comment by lemire** [comment] 2020-04-20 15:30
Meanwhile, C2131 is a genuine error... But how can we be building the code successfully?

**Comment by lemire** [comment] 2020-04-20 15:35
Oh. You are working from the aggregated files, aren't you... we do not test that currently under Visual Studio. In fact, I do not think I have ever tried to compile the single-header files under visual studio.

**Comment by jkeiser** [comment] 2020-04-20 17:11
@lemire the source of the issue is he's stuffing simdjson.cpp and simdjson.h into a new blank VS2019 C++ project (which seems reasonable to me), and the defaults for Visual Studio projects are different from our cmake ones (particularly with these warnings). While it could be the aggregated files, this seems to account for what is happening.

**Comment by lemire** [comment] 2020-04-21 02:57
@jkeiser How do you explain this bit...

```
1>C:\source\repos\ConsoleApplication1\simdjson.cpp(505,97): error C2131: expression did not evaluate to a constant
1>C:\source\repos\ConsoleApplication1\simdjson.cpp(507,3): message : failure was caused by a read of an uninitialized symbol
1>C:\source\repos\ConsoleApplication1\simdjson.cpp(507,3): message : see usage of 'simdjson::internal::$S1'
```

That's the part he proposes to fix by dropping the constexpr. But we know that Visual Studio has no problem with this code... which compiling from CMake. This suggests that something is off...

**Comment by pps83** [comment] 2020-04-21 08:32
As mentioned by @jkeiser, I created a blank new console app project in VS2019 and added there amalgamated simdjson.cpp/sindjson.h. It produces lots of warnings and errors. Some of warnings are set to trigger errors in VS (there is also an option to treat all warnings as errors).

From my quick observation of the warnings (most of them are related to uin32_t to/from size_t conversion). I think, the code should be changed not to use uin32_t in generic code. It should use regular types instead.

In case of that constexpr intizlier_list: if you check individual commit, you can see [my commit message](https://github.com/simdjson/simdjson/pull/738/commits/5a2790a4d6b4d3d327108fa5c98eda3611f78bb3) with explanation:

> available_implementation_pointers is a list of non-constexpr objects that use std::string member variables and virtual function. Attempts to create a constexpr variable from pointers to objects that aren't constexpr results in a compilation error in VS2019

**Comment by stonedreamforest** [comment] 2020-04-23 06:46
```

1>simdjson.cpp
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(4745,25): warning C4244: '=': conversion from 'uint64_t' to 'size_t', possible loss of data
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(5219,27): warning C4244: 'initializing': conversion from 'uint64_t' to 'size_t', possible loss of data
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(5228,71): warning C4244: 'argument': conversion from 'uint64_t' to 'size_t', possible loss of data
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(5268,31): warning C4244: 'initializing': conversion from 'uint64_t' to 'size_t', possible loss of data
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(5326,39): warning C4244: 'argument': conversion from 'T' to 'T', possible loss of data
1>        with
1>        [
1>            T=uint64_t
1>        ]
1>        and
1>        [
1>            T=double
1>        ]
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(5328,38): warning C4244: 'argument': conversion from 'T' to 'T', possible loss of data
1>        with
1>        [
1>            T=int64_t
1>        ]
1>        and
1>        [
1>            T=double
1>        ]
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(5669,27): warning C4244: 'initializing': conversion from 'uint64_t' to 'size_t', possible loss of data
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(6457,14): error C4996: 'simdjson::dom::parser::Iterator': Use the new DOM navigation API instead (see doc/usage.md)
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(6471,29): warning C4244: '=': conversion from 'uint64_t' to 'size_t', possible loss of data
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(6484,14): error C4996: 'simdjson::dom::parser::Iterator': Use the new DOM navigation API instead (see doc/usage.md)
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(6485,24): error C4996: 'simdjson::dom::parser::Iterator': Use the new DOM navigation API instead (see doc/usage.md)
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(6485,5): error C4996: 'simdjson::dom::parser::Iterator': Use the new DOM navigation API instead (see doc/usage.md)
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(6493,14): error C4996: 'simdjson::dom::parser::Iterator': Use the new DOM navigation API instead (see doc/usage.md)
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.cpp(505,97): error C2131: expression did not evaluate to a constant
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.cpp(516,3): message : failure was caused by a read of an uninitialized symbol
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.cpp(516,3): message : see usage of 'simdjson::internal::$S1'
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.cpp(8691,14): warning C4244: 'initializing': conversion from 'uint64_t' to 'double', possible loss of data
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.cpp(8797,21): warning C4244: '+=': conversion from 'uint64_t' to 'int', possible loss of data
1>DataParser.cpp
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(4745,25): warning C4244: '=': conversion from 'uint64_t' to 'size_t', possible loss of data
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(5219,27): warning C4244: 'initializing': conversion from 'uint64_t' to 'size_t', possible loss of data
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(5228,71): warning C4244: 'argument': conversion from 'uint64_t' to 'size_t', possible loss of data
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(5268,31): warning C4244: 'initializing': conversion from 'uint64_t' to 'size_t', possible loss of data
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(5326,39): warning C4244: 'argument': conversion from 'T' to 'T', possible loss of data
1>        with
1>        [
1>            T=uint64_t
1>        ]
1>        and
1>        [
1>            T=double
1>        ]
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(5328,38): warning C4244: 'argument': conversion from 'T' to 'T', possible loss of data
1>        with
1>        [
1>            T=int64_t
1>        ]
1>        and
1>        [
1>            T=double
1>        ]
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(5669,27): warning C4244: 'initializing': conversion from 'uint64_t' to 'size_t', possible loss of data
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(6457,14): error C4996: 'simdjson::dom::parser::Iterator': Use the new DOM navigation API instead (see doc/usage.md)
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(6471,29): warning C4244: '=': conversion from 'uint64_t' to 'size_t', possible loss of data
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(6484,14): error C4996: 'simdjson::dom::parser::Iterator': Use the new DOM navigation API instead (see doc/usage.md)
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(6485,24): error C4996: 'simdjson::dom::parser::Iterator': Use the new DOM navigation API instead (see doc/usage.md)
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(6485,5): error C4996: 'simdjson::dom::parser::Iterator': Use the new DOM navigation API instead (see doc/usage.md)
1>C:\Users\xxfgg\Documents\src\simdjson\simdjson.h(6493,14): error C4996: 'simdjson::dom::parser::Iterator': Use the new DOM navigation API instead (see doc/usage.md)
```

**Comment by stonedreamforest** [comment] 2020-04-23 07:07
turn off the warning as a temporary solution:
![image](https://user-images.githubusercontent.com/16742566/80069301-b86b6280-8573-11ea-8728-e6f10574bd27.png)

But there is a new error：
```
simdjson\simdjson.cpp(426,97): error C2131: expression did not evaluate to a constant
simdjson\simdjson.cpp(437,3): message : failure was caused by a read of an uninitialized symbol
simdjson\simdjson.cpp(437,3): message : see usage of 'simdjson::internal::$S3'
simdjson\simdjson.cpp(5664,16): error C3861: '_umul128': identifier not found
simdjson\simdjson.cpp(8427,3): error C3861: '_BitScanForward64': identifier not found
simdjson\simdjson.cpp(8446,7): error C3861: '_BitScanReverse64': identifier not found

```

**Comment by jkeiser** [comment] 2020-04-23 16:20
@stonedreamforest we've fixed most of the warnings in master, and I've updated the singleheader if you want to give it a whirl. I *think* the only ones left should be a couple of warnings about fopen/fopen_s.

**Comment by jkeiser** [comment] 2020-04-23 16:48
It has a bunch of errors still.

For reference, in a clean solution, these are the flags msbuild passes:

```cmd
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\CL.exe /c /I..\..\include /I..\..\src /ZI /JMC /nologo /W3 /WX- /diagnostics:column /sdl /Od /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"x64\Debug\\" /Fd"x64\Debug\vc142.pdb" /Gd /TP /FC /errorReport:queue ..\..\src\simdjson.cpp quickstart.cpp
```


And the warnings, within the non-singleheader version:

```
  include\simdjson\inline\document.h(342,24): error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  include\simdjson\inline\padded_string.h(105,24): error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  src\implementation.cpp(66,97): error C2131: expression did not evaluate to a constant
  src\implementation.cpp(125,37): error C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  include\simdjson\inline\document.h(342,24): error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
  include\simdjson\inline\padded_string.h(105,24): error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
```

**Comment by jkeiser** [comment] 2020-04-23 16:49
The only other one here is "expression did not evaluate to a constant," which can be fixed by removing constexpr on that line. I'll look at that.

**Comment by lemire** [comment] 2020-04-23 18:46
@jkeiser Why don't I get "error C2131: expression did not evaluate to a constant" in CI?

I compile and run the demo entirely from the single-header files and it looks like everything works fine... down to \WX \W3... 

https://github.com/simdjson/simdjson/pull/778

**Comment by jkeiser** [comment] 2020-04-23 19:37
I don't really know! There sure are a ton of flags on the command line I linked, so it might end up being something from there ...

**Comment by jkeiser** [comment] 2020-04-23 21:43
@lemire I got a little more information this time:

```
src\implementation.cpp(66,97): error C2131: expression did not evaluate to a constant
src\implementation.cpp(68,3): note: failure was caused by a read of an uninitialized symbol
src\implementation.cpp(68,3): note: see usage of 'simdjson::internal::$S1'
```

**Comment by jkeiser** [comment] 2020-04-23 21:44
So it's complaining about haswell_singleton being initialized, I think.

**Comment by jkeiser** [comment] 2020-04-23 22:06
Comparing the Visual Studio and cmake-generated command lines, here are the unique options in each:

Only in Visual Studio cl.exe command line: `/D _CONSOLE /D _DEBUG /D _UNICODE /D UNICODE /FC /JMC /sdl /WX-`

Only in cmake cl.exe command line: `/D _CRT_SECURE_NO_WARNINGS /D _MBCS /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D WIN32 /GR /Ob0 /std:c++17 /WX`

Oh, and when running cl.exe directly using the cl.exe command line, it also printed this:

```
The contents of <string_view> are available only with C++17 or later.
The contents of <optional> are available only with C++17 or later.
```

**Comment by jkeiser** [comment] 2020-04-23 22:10
@lemire aha! Removing the /sdl parameter makes the warning go away.

**Comment by jkeiser** [comment] 2020-04-24 15:04
Bringing this back around: we are down to CRT_SECURE fopen/getenv warnings only at this point!

**Comment by lemire** [comment] 2020-04-25 00:03
> Bringing this back around: we are down to CRT_SECURE fopen/getenv warnings only at this point!

I propose to close this issue now. I will add a remark in the documentation.

**Comment by jkeiser** [comment] 2020-04-25 17:27
It is absolutely the case that simdjson builds with the latest VS2019 now, just with 3-4 warnings.

**Comment by jkeiser** [comment] 2020-04-25 17:28
@pps83 would you mind confirming and reopening if you get anything other than the popen/getenv warnings? (And no errors!)

**Closed by jkeiser** 2020-04-25 17:28 UTC

**Comment by pps83** [comment] 2020-04-25 21:29
> @pps83 would you mind confirming and reopening if you get anything other than the popen/getenv warnings? (And no errors!)

Yes, I had only one getenv and three fopen warnings if I don't suppress them
