### ISSUE TITLE
Error compiling on Fedora 40

### ISSUE THREAD

**Issue by musuruan** [simdjson/simdjson#2217] opened 2024-07-17 17:28 UTC
I hit this bug while trying to package [jazz2](https://github.com/deathkiller/jazz2-native) for Fedora.

jazz2 uses the "singleheader" version. The version used is v3.9.4.

Upstream bug report is available at:
https://github.com/deathkiller/jazz2-native/issues/65

When compiling jazz2 on F40 with Fedora optflags I get the following error:
```
/builddir/build/BUILD/jazz2-native-2.7.0/Sources/simdjson/simdjson.cpp: In function ‘simdjson::fallback::(anonymous namespace)::stage2::tape_builder::parse_document<false>(simdjson::fallback::dom_parser_implementation&, simdjson::dom::document&)simdjson::error_code’:
/builddir/build/BUILD/jazz2-native-2.7.0/Sources/simdjson/simdjson.cpp:16640:49: error: inlining failed in call to ‘always_inline’ ‘simdjson::fallback::(anonymous namespace)::stage2::json_iterator::walk_document<false, simdjson::fallback::(anonymous namespace)::stage2::tape_builder>(simdjson::fallback::(anonymous namespace)::stage2::tape_builder&)simdjson::error_code’: target specific option mismatch
16640 | simdjson_warn_unused simdjson_inline error_code json_iterator::walk_document(V &visitor) noexcept {
      |                                                 ^~~~~~~~~~~~~
/builddir/build/BUILD/jazz2-native-2.7.0/Sources/simdjson/simdjson.cpp:17077:39: note: called from here
17077 |   return iter.walk_document<STREAMING>(builder);
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/builddir/build/BUILD/jazz2-native-2.7.0/Sources/simdjson/simdjson.cpp:16640:49: error: inlining failed in call to ‘always_inline’ ‘simdjson::fallback::(anonymous namespace)::stage2::json_iterator::walk_document<false, simdjson::fallback::(anonymous namespace)::stage2::tape_builder>(simdjson::fallback::(anonymous namespace)::stage2::tape_builder&)simdjson::error_code’: target specific option mismatch
16640 | simdjson_warn_unused simdjson_inline error_code json_iterator::walk_document(V &visitor) noexcept {
      |                                                 ^~~~~~~~~~~~~
/builddir/build/BUILD/jazz2-native-2.7.0/Sources/simdjson/simdjson.cpp:17077:39: note: called from here
17077 |   return iter.walk_document<STREAMING>(builder);
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
gmake[2]: *** [CMakeFiles/jazz2.dir/build.make:1367: CMakeFiles/jazz2.dir/Sources/simdjson/simdjson.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
/builddir/build/BUILD/jazz2-native-2.7.0/Sources/Jazz2/ContentResolver.cpp: In member function ‘Jazz2::ContentResolver::RequestMetadata(Death::Containers::BasicStringView<char const>)’:
/builddir/build/BUILD/jazz2-native-2.7.0/Sources/Jazz2/ContentResolver.cpp:571:48: warning: ‘count’ may be used uninitialized [-Wmaybe-uninitialized]
  571 |                                         } else if (count > 1) {
      |                                                ^~
/builddir/build/BUILD/jazz2-native-2.7.0/Sources/Jazz2/ContentResolver.cpp:486:40: note: ‘count’ was declared here
  486 |                                 size_t count;
      |                                        ^~~~~
gmake[2]: Leaving directory '/builddir/build/BUILD/jazz2-native-2.7.0/redhat-linux-build'
gmake[1]: Leaving directory '/builddir/build/BUILD/jazz2-native-2.7.0/redhat-linux-build'
gmake[1]: *** [CMakeFiles/Makefile2:103: CMakeFiles/jazz2.dir/all] Error 2
gmake: *** [Makefile:159: all] Error 2
```

**Configuration**
 - OS: Fedora 40/x86_64
 - Compiler: gcc  
 - Version 14.1.1
 - Optimization setting: -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer

**Comment by lemire** [comment] 2024-07-17 19:57
Cannot reproduce:

```
$ more /etc/redhat-release
Fedora release 40 (Forty)
$ uname -a
Linux fedora-40 5.14.0-362.13.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Dec 13 14:07:45 UTC 2023 x86_64 GNU/Linux
$ g++ --version
g++ (GCC) 14.1.1 20240701 (Red Hat 14.1.1-7)
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ quickstart.cpp simdjson.cpp  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer
$ ./a.out
100 results.
```

**Comment by lemire** [comment] 2024-07-17 20:15
I am going to close this issue. The reported is using a very recent compiler (GCC 14) against a out-of-date version of simdjson. They report the error against version v3.9.4, but here is what we find at line 16640 in simdjson.cpp, it does not match the error being reported.

<img width="647" alt="Screenshot 2024-07-17 at 4 14 38 PM" src="https://github.com/user-attachments/assets/9ba1722d-7e1a-46e6-b498-e1fddb68ceb7">

**Closed by lemire** 2024-07-17 20:15 UTC
Labels: cannot reproduce
