### ISSUE TITLE
webassembly build supporting SIMD on chrome

### ISSUE THREAD

**Issue by unicomp21** [simdjson/simdjson#1693] opened 2021-08-10 11:52 UTC

**Comment by mko-io** [comment] 2021-08-10 11:55
Even better using WebAssembly SIMD extension, which has been [enabled by default](https://chromestatus.com/feature/6533147810332672) on Chrome 91

**Comment by lemire** [comment] 2021-08-10 12:24
As indicated in issue https://github.com/simdjson/simdjson/issues/35, it is an open project and everyone can contribute. However, we do not need an issue to track this unless there are people working on the issue.

@unicomp21 and @mko-io : what are your plans... do you expect to be able to produce a pull request?

If not, I am going to close this issue.

**Comment by mko-io** [comment] 2021-08-11 14:50
@lemire I just want it on the roadmap, I'm not capable to implement this feature, If no one has time to do it, feel free to close this issue for now

**Comment by lemire** [comment] 2021-08-12 22:18
I am going to close this. If someone has the time and expertise, or the financially backing, to work on this issue, please speak up... otherwise, I think the issue is not helpful.

**Closed** 2021-08-12 22:18 UTC
