### ISSUE TITLE
API for error locations?

### ISSUE THREAD

**Issue by strager** [simdjson/simdjson#1657] opened 2021-07-16 05:04 UTC
**Is your feature request related to a problem? Please describe.**
When parsing an malformed JSON document (using simdjson's OnDemand API), simdjson provides little information to a human on what the error is.

**Describe the solution you'd like**
Functions for `document` or `parser` which return the byte offset or `string_view` of the erroneous character or token.

**Describe alternatives you've considered**
On parse error, `simdjson_result` could store the byte offset or `string_view` of the erroneous character or token.

I could parse malformed JSON with a different JSON library to get human-friendly error information. However, this would worsen performance (slightly) and bloat my executable's size.

**Additional context**
Malformed JSON documents are common because I am using simdjson as part of an interactive text editor. Immediately when the text document changes in the editor, I parse the JSON, extract information, and do some other work. When typing into an editor, a human will often write malformed JSON (e.g. trailing commas, unclosed strings, and missing object values). I want to indicate to the human that the JSON has invalid syntax by highlighting some offending text (e.g. with a squiggly underline).

**Are you willing to contribute code or documentation toward this new feature?**
Yes.

**Comment by lemire** [comment] 2021-07-16 13:15
Duplicate of https://github.com/simdjson/simdjson/issues/237

Generally speaking, simdjson is optimized for  a context where JSON documents are valid and were invalid documents are an exceptional condition. Nevertheless, we could certainly improve our error reporting, as you indicate.

**Closed by lemire** 2021-07-16 13:15 UTC
