### ISSUE TITLE
[SOLVED] ambiguous template specialization 'get<simdjson::fallback::ondemand::document>'

### ISSUE THREAD

**Issue by MikTur** [simdjson/simdjson#2104] opened 2024-01-07 02:26 UTC
Hi I am getting partial template specialization errors when trying to compile the basic example using the twitter.json (as is).

All these seems to be broken for my gcc 7.3 compiler:
```

template<> simdjson_inline simdjson_result<array> document::get() & noexcept { return get_array(); }
template<> simdjson_inline simdjson_result<object> document::get() & noexcept { return get_object(); }
template<> simdjson_inline simdjson_result<raw_json_string> document::get() & noexcept { return get_raw_json_string(); }
template<> simdjson_inline simdjson_result<std::string_view> document::get() & noexcept { return get_string(false); }
template<> simdjson_inline simdjson_result<double> document::get() & noexcept { return get_double(); }
template<> simdjson_inline simdjson_result<uint64_t> document::get() & noexcept { return get_uint64(); }
template<> simdjson_inline simdjson_result<int64_t> document::get() & noexcept { return get_int64(); }
template<> simdjson_inline simdjson_result<bool> document::get() & noexcept { return get_bool(); }
template<> simdjson_inline simdjson_result<value> document::get() & noexcept { return get_value(); }

template<> simdjson_inline simdjson_result<raw_json_string> document::get() && noexcept { return get_raw_json_string(); }
template<> simdjson_inline simdjson_result<std::string_view> document::get() && noexcept { return get_string(false); }
template<> simdjson_inline simdjson_result<double> document::get() && noexcept { return std::forward<document>(*this).get_double(); }
template<> simdjson_inline simdjson_result<uint64_t> document::get() && noexcept { return std::forward<document>(*this).get_uint64(); }
template<> simdjson_inline simdjson_result<int64_t> document::get() && noexcept { return std::forward<document>(*this).get_int64(); }
template<> simdjson_inline simdjson_result<bool> document::get() && noexcept { return std::forward<document>(*this).get_bool(); }
template<> simdjson_inline simdjson_result<value> document::get() && noexcept { return get_value(); }
```

This is my plain cmake file:

```
cmake_minimum_required (VERSION 3.0)

cmake_policy(SET CMP0074 OLD)

project (tes_simdjson)

set (CMAKE_CXX_STANDARD 17)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")

set(SimdJson_DIR "/c/ogre3d_dependencies_mingw")
find_package(SimdJson REQUIRED)

#message(STATUS "${SIMDJSON_INCLUDE_DIRS}")
message(STATUS "${SimdJson_DIR}/include")

add_executable(${PROJECT_NAME} main.cpp)

target_include_directories(${PROJECT_NAME} PUBLIC "${SimdJson_DIR}/include")
target_link_libraries(${PROJECT_NAME} PUBLIC ${SIMDJSON_LIBRARIES})

```

For every one of the specializations I get:
```

C:\ogre3d_dependencies_mingw\include\simdjson.h:41655: error: ambiguous template specialization 'get<>' for 'simdjson::simdjson_result<simdjson::fallback::ondemand::array> simdjson::fallback::ondemand::document::get() &'
In file included from C:/tmp/test_simdjson/main.cpp:2:0:
C:/ogre3d_dependencies_mingw/include/simdjson.h:41655:51: error: ambiguous template specialization 'get<>' for 'simdjson::simdjson_result<simdjson::fallback::ondemand::array> simdjson::fallback::ondemand::document::get() &'
 template<> simdjson_inline simdjson_result<array> document::get() & noexcept { return get_array(); }
                                                   ^~~~~~~~
C:/ogre3d_dependencies_mingw/include/simdjson.h:39661:59: note: candidates are: template<class T> simdjson::simdjson_result<T> simdjson::fallback::ondemand::document::get() &
   template<typename T> simdjson_inline simdjson_result<T> get() & noexcept {
                                                           ^~~
C:/ogre3d_dependencies_mingw/include/simdjson.h:39670:59: note:                 template<class T> simdjson::simdjson_result<T> simdjson::fallback::ondemand::document::get() &&
   template<typename T> simdjson_inline simdjson_result<T> get() && noexcept {
                                                           ^~~
```

The same happens when I am trying to deploy the library with dev mode flag which in turn compiles few tests.

Thanks.

**Comment by MikTur** [comment] 2024-01-07 13:38
C++ for dummies:
Many compilers, especially the ones a bit outdated do handle && as & also.
I had to modify the getters signature with & to be const &

**Comment by lemire** [comment] 2024-01-07 16:25
I cannot verify. The reporter has indicated the issue is resolved. Closing.

**Closed by lemire** 2024-01-07 16:25 UTC
